export const PLAYGROUND_FIELD_HELP = {
  texture: "Choose the image or video used as the source.",
  canvasWidth: "Set the output canvas width in pixels.",
  canvasHeight: "Set the output canvas height in pixels.",
  shaderEnabled: "Turn the stripe shader on or off.",
  backgroundColor: "Set the canvas background color. Ignored while canvas CSS is filled in.",
  canvasCss: "Add CSS background declarations behind the canvas.",
  stripesEnabled: "Show or hide the stripe overlay.",
  stripeColor: "Set the stripe color.",
  stripeThreshold: "Set where this stripe begins in luminance.",
  stripeWidth: "Set how wide this stripe band is.",
  textureLuminanceMode:
    "Luminance maps brightness to stripes. Overlay keeps the source visible and draws the loudest three stripe colors on top. Colors replaces fills with vivid source hues.",
  textureBackgroundColor: "Reference color for chroma distance in Colors mode. Pixels near this color contribute less.",
  colorsStripeThreshold: "Minimum chroma presence for this stripe band. Higher values require more vivid source color.",
  colorsStripeWidth: "Stripe thickness in pixels for this chroma band. Cell fill uses the most vivid source color.",
  sparkleGapsActiveRatio: "Control how often gap sparkle is active.",
  sparkleGapsSpeed: "Control how fast gap sparkle pulses.",
  sparkleWidthActiveRatio: "Control how often width sparkle is active.",
  sparkleWidthSpeed: "Control how fast width sparkle pulses.",

  exposure: "Raises or lowers source light before mapping.",
  brightness: "Shifts the source lighter or darker.",
  contrast: "Expands or softens light and dark differences.",
  gamma: "Changes midtone brightness without moving endpoints.",
  invertLuminance: "Flip dark and light source values.",
  blackPoint: "Pixels darker than this become the darkest stripe.",
  whitePoint: "Pixels brighter than this become the lightest stripe.",
  thresholdBias: "Shift stripe thresholds lighter or darker.",
  posterize: "Reduce luminance into fewer steps.",
  noise: "Add random texture to luminance values.",
  blur: "Box-blur the source in pixel space before tone mapping and stripe sampling.",
  sharpen: "Increase edge contrast before mapping.",
  fit: "Choose how the source fills the canvas.",
  zoom: "Scale the source inside the canvas.",
  panX: "Move the source left or right.",
  panY: "Move the source up or down.",

  cellWidth: "Set each grid cell's width in pixels.",
  cellHeight: "Set each grid cell's height in pixels.",
  gapX: "Set horizontal space between cells.",
  gapY: "Set vertical space between cells.",
  cornerRadius: "Round the corners of stripe cells.",
  orientation: "Choose whether stripes run vertically or horizontally.",
  letterSize: "Set the letter font size.",
  letterRatio: "Control how many eligible cells show letters.",
  letterCharset: "Choose which characters can appear.",
  letterColor: "Set the letter color.",
  letterShuffleSpeed: "Control how quickly letters change.",
  gapPeriodMin: "Set the shortest gap sparkle duration.",
  gapPeriodMax: "Set the longest gap sparkle duration.",
  widthPeriodMin: "Set the shortest width shuffle duration.",
  widthPeriodMax: "Set the longest width shuffle duration.",
  widthSwing: "Set how far stripe widths can shift.",
  processingInterval: "Set how often stripe processing updates the grid.",

  flamesEnabled:
    "Show or hide flame streaks in preview (colored from the texture), stripe sampling, and Copy SVG export.",
  flamesDirection: "Travel direction for flame streaks across the canvas.",
  flamesWidthMin: "Minimum flame width as a percent of canvas width.",
  flamesWidthMax: "Maximum flame width as a percent of canvas width.",
  flamesHeightMin: "Minimum flame height as a percent of canvas height.",
  flamesHeightMax: "Maximum flame height as a percent of canvas height.",
  flamesSpeed: "Base travel speed for new flames in pixels per second.",
  flamesSpeedVariation: "How much each flame's speed varies around the base (0 = uniform).",
  flamesSpawnInterval: "Average milliseconds between new flames spawning at the travel edge.",
  flamesSpawnJitter: "Random milliseconds added or subtracted from the spawn interval.",
  flamesMaxActive: "Maximum number of flame rects on screen at once.",
  flamesEdgeSharpness:
    "Gradient plateau width across streak thickness (0 = wide solid core, looks harder; 1 = narrow core with longer fades).",
  flamesOpacityMin: "Minimum peak opacity for each flame streak (0–1).",
  flamesOpacityMax: "Maximum peak opacity for each flame streak (0–1).",
  flamesEdgeMaskEnabled:
    "Reduce how much flames brighten luminance near canvas edges (preview texture and stripe width sampling). Stripe opacity stays unchanged.",
  flamesEdgeMaskStart: "Inset from each canvas edge where masked flame luminance stays 0 (percent of width/height).",
  flamesEdgeMaskEnd:
    "Inset from each canvas edge where masked flame luminance reaches full strength. Must be greater than mask start.",
  flamesEdgeMaskPower: "Curve shaping for the flame luminance ramp (1 = linear, higher = softer mid-fade).",

  revealEnabled: "Show or hide the reveal animation applied before stripe thresholds are calculated.",
  revealType: "Reveal style: Wave expands a feathered front; Assembly flies glowing circles in to build the texture.",
  revealAssemblyOrder: "Order cells assemble in: from the center out, the edges in, a left-to-right sweep, or random.",
  revealSpeedMin:
    "Fastest cells: shortest per-cell fly-in time (ms). Each cell picks a random travel time between min and max.",
  revealSpeedMax:
    "Slowest cells: longest per-cell fly-in time (ms). Each cell picks a random travel time between min and max.",
  revealSpread: "How staggered the arrivals are. Low = all circles land together; high = a long progressive wave.",
  revealPreset: "Choose the reveal animation applied before stripe thresholds are calculated.",
  revealPosition: "Choose where the wave starts on the canvas.",
  revealDuration: "How long the reveal takes from start to fully visible.",
  revealSoftness: "Width of the wave edge transition.",
  revealWaviness: "How uneven the circular wave edge becomes.",
  revealNoiseScale: "Size of the deterministic wave-edge ripples.",
  revealColumnStagger: "How far column start times spread across the reveal.",
  revealColumnYShift: "Maximum random vertical column offset as a ratio of grid height. Set to 0 for no shift.",

  cursorTrailEnabled: "Enable the pointer fluid trail in sampled pixels before stripe calculation.",
  cursorTrailParticleRadius: "Base size of each fluid density particle.",
  cursorTrailParticleAlpha: "How strongly each particle brightens the sampled texture.",
  cursorTrailParticleLife: "How long particles remain active.",
  cursorTrailParticleLifeJitter: "Random extra lifetime added per particle.",
  cursorTrailSpacing: "Distance between emitted particles. Lower values spawn more frequently.",
  cursorTrailMaxEmit: "Maximum particles emitted in one frame.",
  cursorTrailVelocitySmoothing: "How much emitter velocity is smoothed. Higher feels steadier and slower.",
  cursorTrailVelocityScale: "How much pointer movement velocity is transferred into particles.",
  cursorTrailTangentVelocity: "Sideways velocity that makes the trail spread and swirl.",
  cursorTrailDamping: "How quickly particle velocity decays. Lower values slow the trail faster.",
  cursorTrailSpreadMin: "Minimum random spawn offset around the pointer path.",
  cursorTrailSpreadMax: "Maximum random spawn offset around the pointer path.",
  cursorTrailSpin: "Curl amount applied while particles drift.",
  cursorTrailDensityRadiusMin: "Base density radius multiplier as particles fade.",
  cursorTrailDensityRadiusLife: "Extra density radius multiplier while particles are young.",
  cursorTrailPushStrength:
    "How far source pixels are pushed away from the trail before stripe calculation (capped at two cells).",
  cursorTrailPushRadius: "Radius multiplier for the texture displacement around the trail.",
  cursorTrailPushLag: "How far the texture push trails behind particle movement.",
  cursorTrailPushWobble: "Small offset so the texture push does not match the white trail exactly.",

  cursorClickEnabled: "Enable click ripples in sampled pixels before stripe calculation.",
  cursorClickLife: "How long each click ripple lasts in milliseconds.",
  cursorClickStartRadius: "Starting radius of the ripple ring in display pixels.",
  cursorClickMaxRadius: "Maximum radius the ripple expands to before fading out.",
  cursorClickStartStroke: "Starting ring stroke width. The band thins as the ripple grows.",
  cursorClickEndStroke: "Final ring stroke width at the end of the ripple life.",
  cursorClickMaxWaves: "Maximum simultaneous click ripples on screen.",
  cursorClickPushStrength:
    "Peak radial push at click birth (capped at two cells). The tear hole opens behind the expanding front.",
  cursorClickPushBandScale: "Multiplier on stroke width for how wide the push displacement band is.",
  cursorClickRingWhite: "White brighten on the leading ring edge. Feeds lighter stripe cells.",
  debugStage:
    "Debug view: Normal renders the app; Source shows the raw texture; Field shows the render field (grayscale, white = render a stripe), overlays hidden.",
} as const;
