export const PLAYGROUND_FIELD_HELP = {
  texture: "Choose the image, video, or shader equation used as the source.",
  colorPreset:
    "Apply a saved color palette to the stripes (and overlay stripes). Use Save color preset to keep the current palette so you can reuse it on any texture; editing colors switches this to Custom.",
  shaderPreset:
    "Load a starting-point equation. Waveform presets render in a single cheap 2D pass; the raymarch preset is the heavy original. Your saved shaders appear here too. Editing the equation switches this to Custom — use Save shader to keep it.",
  shaderSource:
    "ShaderToy-style GLSL with a mainImage(out vec4, vec2) entry point. Uses iTime, iResolution, and iChannel0–3 uniforms. Tweak the constants block at the top to reshape waveform presets. Texture Source zoom/pan applies to the equation when fit is Stretch. Enable Audio input to feed the live microphone into iChannel0.",
  audioInput:
    "Capture the microphone and feed it into iChannel0 as a ShaderToy-style audio texture (row 0 = FFT spectrum, row 1 = waveform). Sample it with texture(iChannel0, vec2(x, 0.25)).x for the spectrum. Requires microphone permission.",
  canvasWidth: "Set the output canvas width in pixels.",
  canvasHeight: "Set the output canvas height in pixels.",
  renderScale:
    "GPU backing-store resolution multiplier. 2x is sharpest; drop to 1x or 0.5x for a big fps boost on slower GPUs (stripes soften slightly). Video export captures at this resolution; SVG/React exports are unaffected.",
  shaderEnabled: "Turn the stripe shader on or off.",
  backgroundColor: "Set the canvas background color. Ignored while canvas CSS is filled in.",
  canvasCss: "Add CSS background declarations behind the canvas.",
  stripesEnabled: "Show or hide the stripe overlay.",
  stripeColor: "Set the stripe color.",
  stripeThreshold: "Set where this stripe begins in luminance.",
  stripeWidth: "Set how wide this stripe band is.",
  textureLuminanceMode:
    "Luminance maps brightness to stripes. Overlay keeps the source visible and draws the loudest three stripe colors on top. Colors replaces fills with vivid source hues.",
  textureBackgroundColor: "Reference color for chroma distance in Colors mode. Pixels near this color contribute less.",
  colorsStripeThreshold: "Minimum chroma presence for this stripe band. Higher values require more vivid source color.",
  colorsStripeWidth: "Stripe thickness in pixels for this chroma band. Cell fill uses the most vivid source color.",
  sparkleGapsActiveRatio: "Control how often gap sparkle is active.",
  sparkleGapsSpeed: "Control how fast gap sparkle pulses.",
  sparkleWidthActiveRatio: "Control how often width sparkle is active.",
  sparkleWidthSpeed: "Control how fast width sparkle pulses.",

  exposure: "Raises or lowers source light before mapping.",
  brightness: "Shifts the source lighter or darker.",
  contrast: "Expands or softens light and dark differences.",
  gamma: "Changes midtone brightness without moving endpoints.",
  invertLuminance: "Flip dark and light source values.",
  blackPoint: "Pixels darker than this become the darkest stripe.",
  whitePoint: "Pixels brighter than this become the lightest stripe.",
  thresholdBias: "Shift stripe thresholds lighter or darker.",
  posterize: "Reduce luminance into fewer steps.",
  noise: "Add random texture to luminance values.",
  blur: "Box-blur the source in pixel space before tone mapping and stripe sampling.",
  sharpen: "Increase edge contrast before mapping.",
  fit: "Choose how the source fills the canvas.",
  zoom: "Scale the source inside the canvas.",
  panX: "Move the source left or right.",
  panY: "Move the source up or down.",

  cellWidth: "Set each grid cell's width in pixels.",
  cellHeight: "Set each grid cell's height in pixels.",
  gapX: "Set horizontal space between cells.",
  gapY: "Set vertical space between cells.",
  cornerRadius: "Round the corners of stripe cells.",
  orientation: "Choose whether stripes run vertically or horizontally.",
  letterSize: "Set the letter font size.",
  letterRatio: "Control how many eligible cells show letters.",
  letterCharset: "Choose which characters can appear.",
  letterColor: "Set the letter color.",
  letterShuffleSpeed: "Control how quickly letters change.",
  gapPeriodMin: "Set the shortest gap sparkle duration.",
  gapPeriodMax: "Set the longest gap sparkle duration.",
  widthPeriodMin: "Set the shortest width shuffle duration.",
  widthPeriodMax: "Set the longest width shuffle duration.",
  widthSwing: "Set how far stripe widths can shift.",
  processingInterval: "Set how often stripe processing updates the grid.",

  flamesEnabled:
    "Show or hide flame streaks in preview (colored from the texture), stripe sampling, and Copy SVG export.",
  flamesDirection: "Travel direction for flame streaks across the canvas.",
  flamesWidthMin: "Minimum flame width as a percent of canvas width.",
  flamesWidthMax: "Maximum flame width as a percent of canvas width.",
  flamesHeightMin: "Minimum flame height as a percent of canvas height.",
  flamesHeightMax: "Maximum flame height as a percent of canvas height.",
  flamesSpeed: "Base travel speed for new flames in pixels per second.",
  flamesSpeedVariation: "How much each flame's speed varies around the base (0 = uniform).",
  flamesSpawnInterval: "Average milliseconds between new flames spawning at the travel edge.",
  flamesSpawnJitter: "Random milliseconds added or subtracted from the spawn interval.",
  flamesMaxActive: "Maximum number of flame rects on screen at once.",
  flamesEdgeSharpness:
    "Gradient plateau width across streak thickness (0 = wide solid core, looks harder; 1 = narrow core with longer fades).",
  flamesOpacityMin: "Minimum peak opacity for each flame streak (0–1).",
  flamesOpacityMax: "Maximum peak opacity for each flame streak (0–1).",
  flamesEdgeMaskEnabled:
    "Reduce how much flames brighten luminance near canvas edges (preview texture and stripe width sampling). Stripe opacity stays unchanged.",
  flamesEdgeMaskStart: "Inset from each canvas edge where masked flame luminance stays 0 (percent of width/height).",
  flamesEdgeMaskEnd:
    "Inset from each canvas edge where masked flame luminance reaches full strength. Must be greater than mask start.",
  flamesEdgeMaskPower: "Curve shaping for the flame luminance ramp (1 = linear, higher = softer mid-fade).",

  revealEnabled: "Show or hide the reveal animation applied before stripe thresholds are calculated.",
  revealPreset: "Choose the reveal animation applied before stripe thresholds are calculated.",
  revealPosition: "Choose where the wave starts on the canvas.",
  revealDuration: "How long the reveal takes from start to fully visible.",
  revealSoftness: "Width of the wave edge transition.",
  revealWaviness: "How uneven the circular wave edge becomes.",
  revealNoiseScale: "Size of the deterministic wave-edge ripples.",
  revealColumnStagger: "How far column start times spread across the reveal.",
  revealColumnYShift: "Maximum random vertical column offset as a ratio of grid height. Set to 0 for no shift.",

  cursorTrailEnabled: "Enable the pointer fluid trail in sampled pixels before stripe calculation.",
  cursorTrailParticleRadius: "Base size of each fluid density particle.",
  cursorTrailParticleAlpha: "How strongly each particle brightens the sampled texture.",
  cursorTrailParticleLife: "How long particles remain active.",
  cursorTrailParticleLifeJitter: "Random extra lifetime added per particle.",
  cursorTrailSpacing: "Distance between emitted particles. Lower values spawn more frequently.",
  cursorTrailMaxEmit: "Maximum particles emitted in one frame.",
  cursorTrailVelocitySmoothing: "How much emitter velocity is smoothed. Higher feels steadier and slower.",
  cursorTrailVelocityScale: "How much pointer movement velocity is transferred into particles.",
  cursorTrailTangentVelocity: "Sideways velocity that makes the trail spread and swirl.",
  cursorTrailDamping: "How quickly particle velocity decays. Lower values slow the trail faster.",
  cursorTrailSpreadMin: "Minimum random spawn offset around the pointer path.",
  cursorTrailSpreadMax: "Maximum random spawn offset around the pointer path.",
  cursorTrailSpin: "Curl amount applied while particles drift.",
  cursorTrailDensityRadiusMin: "Base density radius multiplier as particles fade.",
  cursorTrailDensityRadiusLife: "Extra density radius multiplier while particles are young.",
  cursorTrailPushStrength:
    "How far source pixels are pushed away from the trail before stripe calculation (capped at two cells).",
  cursorTrailPushRadius: "Radius multiplier for the texture displacement around the trail.",
  cursorTrailPushLag: "How far the texture push trails behind particle movement.",
  cursorTrailPushWobble: "Small offset so the texture push does not match the white trail exactly.",

  cursorClickEnabled: "Enable click ripples in sampled pixels before stripe calculation.",
  cursorClickLife: "How long each click ripple lasts in milliseconds.",
  cursorClickStartRadius: "Starting radius of the ripple ring in display pixels.",
  cursorClickMaxRadius: "Maximum radius the ripple expands to before fading out.",
  cursorClickStartStroke: "Starting ring stroke width. The band thins as the ripple grows.",
  cursorClickEndStroke: "Final ring stroke width at the end of the ripple life.",
  cursorClickMaxWaves: "Maximum simultaneous click ripples on screen.",
  cursorClickPushStrength:
    "Peak radial push at click birth (capped at two cells). The tear hole opens behind the expanding front.",
  cursorClickPushBandScale: "Multiplier on stroke width for how wide the push displacement band is.",
  cursorClickRingWhite: "White brighten on the leading ring edge. Feeds lighter stripe cells.",
  perfStatus:
    "Perf overlay state. Enabled by default in dev. Override with globalThis.__PLAYGROUND_PERF__ = true/false in devtools.",
  perfHealth: "Quick signal of overall runtime health (good, ok, or slow).",
  perfFps: "Instantaneous frames per second from the latest frame delta.",
  perfFpsSmoothed: "Smoothed FPS trend for easier readability while scrubbing.",
  perfFrameBudgetUsage: "How much of a 60 FPS frame budget this tick consumed.",
  perfFrameHeadroom: "How many milliseconds remain before missing a 60 FPS frame budget.",
  perfTickTotal: "Total time spent in one scene tick.",
  perfRender: "Time spent rendering the Pixi frame.",
  perfBuildGrid: "Time spent building the stripe block grid.",
  perfSampleFrame: "Time spent sampling source frame pixels.",
  perfBlockTexture: "Time spent uploading block-grid textures.",
  perfWorkerLatency: "Main-thread submit -> worker result latency.",
  perfWorkerQueueDepth: "Current async worker queue depth.",
  perfWorkerInFlight: "Whether a worker grid build is currently running.",
  perfWorkerApplied: "Whether this tick applied a worker-produced grid.",
  perfWorkerCoalesced: "Count of worker requests coalesced into newer ones.",
  perfWorkerDroppedQueued: "Count of queued requests replaced before execution.",
  perfPartialGrid: "Whether this tick used a partial grid rebuild.",
} as const;
