/** UI slider bounds for playground duotone tuning. */
export const PLAYGROUND_CONTROL_RANGES = {
  /** Active cell ratio 0–1 (0 = off). Default 0.22. */
  sparkleGapsActivePercent: { min: 0, max: 1, step: 0.01 },
  /** Pulse speed factor. Default 1. Slider 0.5–1.5. */
  sparkleGapsSpeed: { min: 0.5, max: 1.5, step: 0.05 },
  /** Active cell ratio 0–1 (0 = off). Default 0.3. */
  sparkleWidthActivePercent: { min: 0, max: 1, step: 0.01 },
  sparkleWidthSpeed: { min: 0.5, max: 1.5, step: 0.05 },
  /** Texture luminance gamma (positive only). Default 1. */
  textureGamma: { min: 0.05, max: 5, step: 0.05 },
  flamesSizeRatio: { min: 0.001, max: 0.08, step: 0.0005 },
  flamesSpeed: { min: 10, max: 200, step: 1 },
  flamesSpeedVariation: { min: 0, max: 1, step: 0.01 },
  flamesSpawnIntervalMs: { min: 50, max: 2000, step: 10 },
  flamesSpawnJitterMs: { min: 0, max: 500, step: 5 },
  flamesMaxActive: { min: 1, max: 120, step: 1 },
  flamesEdgeSharpness: { min: 0, max: 1, step: 0.01 },
  flamesEdgeMaskInset: { min: 0, max: 50, step: 0.1 },
  flamesEdgeMaskPower: { min: 0.1, max: 4, step: 0.05 },
  revealDurationMs: { min: 100, max: 6000, step: 50 },
  revealSoftness: { min: 0, max: 0.5, step: 0.01 },
  revealWaviness: { min: 0, max: 0.35, step: 0.01 },
  revealNoiseScale: { min: 0.5, max: 16, step: 0.1 },
  revealColumnStagger: { min: 0, max: 1, step: 0.01 },
  revealColumnYShift: { min: 0, max: 1, step: 0.01 },
  cursorTrailParticleRadius: { min: 2, max: 40, step: 0.5 },
  cursorTrailParticleAlpha: { min: 0, max: 1, step: 0.01 },
  cursorTrailParticleLife: { min: 100, max: 4000, step: 10 },
  cursorTrailParticleLifeJitter: { min: 0, max: 1000, step: 10 },
  cursorTrailSpacing: { min: 0.5, max: 20, step: 0.5 },
  cursorTrailMaxEmit: { min: 1, max: 80, step: 1 },
  cursorTrailVelocitySmoothing: { min: 0, max: 0.95, step: 0.01 },
  cursorTrailVelocityScale: { min: 0, max: 1, step: 0.01 },
  cursorTrailTangentVelocity: { min: 0, max: 4, step: 0.05 },
  cursorTrailDamping: { min: 0.8, max: 1, step: 0.01 },
  cursorTrailSpreadMin: { min: 0, max: 20, step: 0.5 },
  cursorTrailSpreadMax: { min: 0, max: 30, step: 0.5 },
  cursorTrailSpin: { min: 0, max: 0.08, step: 0.001 },
  cursorTrailDensityRadiusMin: { min: 0, max: 2, step: 0.05 },
  cursorTrailDensityRadiusLife: { min: 0, max: 2, step: 0.05 },
  cursorTrailPushStrength: { min: 0, max: 40, step: 0.5 },
  cursorTrailPushRadius: { min: 0, max: 6, step: 0.05 },
  cursorTrailPushLag: { min: 0, max: 20, step: 0.5 },
  cursorTrailPushWobble: { min: 0, max: 12, step: 0.5 },
  cursorTrailScale: { min: 0, max: 1, step: 0.01 },
  clickWaveLifeMs: { min: 200, max: 4000, step: 10 },
  clickWaveStartRadius: { min: 1, max: 80, step: 1 },
  clickWaveMaxRadius: { min: 20, max: 400, step: 1 },
  clickWaveStartStroke: { min: 1, max: 60, step: 0.5 },
  clickWaveEndStroke: { min: 0.25, max: 20, step: 0.25 },
  clickWaveMaxWaves: { min: 1, max: 24, step: 1 },
  clickWavePushStrength: { min: 0, max: 80, step: 0.5 },
  clickWavePushBandScale: { min: 1, max: 6, step: 0.1 },
  clickWaveRingWhite: { min: 0, max: 1, step: 0.01 },
  clickWaveSliceWhite: { min: 0, max: 1, step: 0.01 },
  clickWaveSliceCountMin: { min: 3, max: 48, step: 1 },
  clickWaveSliceCountMax: { min: 3, max: 64, step: 1 },
  clickWaveSliceSkipMin: { min: 0, max: 0.9, step: 0.01 },
  clickWaveSliceSkipMax: { min: 0, max: 0.95, step: 0.01 },
  clickWaveSliceLevelMin: { min: 2, max: 12, step: 1 },
  clickWaveSliceLevelMax: { min: 2, max: 16, step: 1 },
} as const;

/** Wider bounds for typed values (sliders stay on PLAYGROUND_CONTROL_RANGES). */
export const PLAYGROUND_CONTROL_INPUT_BOUNDS = {
  sparkleGapsActivePercent: { min: 0, max: 1 },
  sparkleGapsSpeed: { min: 0.05, max: 100 },
  sparkleWidthActivePercent: { min: 0, max: 1 },
  sparkleWidthSpeed: { min: 0.05, max: 100 },
  /** Typed gamma; slider stays on PLAYGROUND_CONTROL_RANGES.textureGamma. */
  textureGamma: { min: 0.05, max: 1_000 },
  flamesSizeRatio: { min: 0.0005, max: 0.5 },
  flamesSpeed: { min: 1, max: 500 },
  flamesSpeedVariation: { min: 0, max: 1 },
  flamesSpawnIntervalMs: { min: 20, max: 10_000 },
  flamesSpawnJitterMs: { min: 0, max: 5000 },
  flamesMaxActive: { min: 1, max: 200 },
  flamesEdgeSharpness: { min: 0, max: 1 },
  flamesEdgeMaskInset: { min: 0, max: 50 },
  flamesEdgeMaskPower: { min: 0.1, max: 4 },
  revealDurationMs: { min: 100, max: 30_000 },
  revealSoftness: { min: 0, max: 1 },
  revealWaviness: { min: 0, max: 1 },
  revealNoiseScale: { min: 0.1, max: 50 },
  revealColumnStagger: { min: 0, max: 1 },
  revealColumnYShift: { min: 0, max: 1 },
  cursorTrailParticleRadius: { min: 0.5, max: 80 },
  cursorTrailParticleAlpha: { min: 0, max: 1 },
  cursorTrailParticleLife: { min: 50, max: 10_000 },
  cursorTrailParticleLifeJitter: { min: 0, max: 10_000 },
  cursorTrailSpacing: { min: 0.5, max: 80 },
  cursorTrailMaxEmit: { min: 1, max: 200 },
  cursorTrailVelocitySmoothing: { min: 0, max: 0.98 },
  cursorTrailVelocityScale: { min: 0, max: 2 },
  cursorTrailTangentVelocity: { min: 0, max: 20 },
  cursorTrailDamping: { min: 0, max: 1 },
  cursorTrailSpreadMin: { min: 0, max: 80 },
  cursorTrailSpreadMax: { min: 0, max: 120 },
  cursorTrailSpin: { min: 0, max: 0.2 },
  cursorTrailDensityRadiusMin: { min: 0, max: 3 },
  cursorTrailDensityRadiusLife: { min: 0, max: 3 },
  cursorTrailPushStrength: { min: 0, max: 120 },
  cursorTrailPushRadius: { min: 0, max: 8 },
  cursorTrailPushLag: { min: 0, max: 80 },
  cursorTrailPushWobble: { min: 0, max: 80 },
  cursorTrailScale: { min: 0, max: 1 },
  clickWaveLifeMs: { min: 80, max: 10_000 },
  clickWaveStartRadius: { min: 1, max: 120 },
  clickWaveMaxRadius: { min: 4, max: 600 },
  clickWaveStartStroke: { min: 0.5, max: 80 },
  clickWaveEndStroke: { min: 0.25, max: 40 },
  clickWaveMaxWaves: { min: 1, max: 32 },
  clickWavePushStrength: { min: 0, max: 200 },
  clickWavePushBandScale: { min: 1, max: 8 },
  clickWaveRingWhite: { min: 0, max: 1 },
  clickWaveSliceWhite: { min: 0, max: 1 },
  clickWaveSliceCountMin: { min: 3, max: 64 },
  clickWaveSliceCountMax: { min: 3, max: 64 },
  clickWaveSliceSkipMin: { min: 0, max: 0.95 },
  clickWaveSliceSkipMax: { min: 0, max: 0.95 },
  clickWaveSliceLevelMin: { min: 2, max: 16 },
  clickWaveSliceLevelMax: { min: 2, max: 16 },
} as const;
