export const PLAYGROUND_FIELD_HELP = {
  texture: "Choose the image or video used as the source.",
  canvasWidth: "Set the output canvas width in pixels.",
  canvasHeight: "Set the output canvas height in pixels.",
  shaderEnabled: "Turn the stripe shader on or off.",
  canvasCss: "Add CSS background declarations behind the canvas.",
  stripesEnabled: "Show or hide the stripe overlay.",
  stripeColor: "Set the stripe color.",
  stripeThreshold: "Set where this stripe begins in luminance.",
  stripeWidth: "Set how wide this stripe band is.",
  sparkleGapsActiveRatio: "Control how often gap sparkle is active.",
  sparkleGapsSpeed: "Control how fast gap sparkle pulses.",
  sparkleWidthActiveRatio: "Control how often width sparkle is active.",
  sparkleWidthSpeed: "Control how fast width sparkle pulses.",

  exposure: "Raises or lowers source light before mapping.",
  brightness: "Shifts the source lighter or darker.",
  contrast: "Expands or softens light and dark differences.",
  gamma: "Changes midtone brightness without moving endpoints.",
  invertLuminance: "Flip dark and light source values.",
  blackPoint: "Pixels darker than this become the darkest stripe.",
  whitePoint: "Pixels brighter than this become the lightest stripe.",
  thresholdBias: "Shift stripe thresholds lighter or darker.",
  posterize: "Reduce luminance into fewer steps.",
  noise: "Add random texture to luminance values.",
  blur: "Smooth source luminance before mapping.",
  sharpen: "Increase edge contrast before mapping.",
  fit: "Choose how the source fills the canvas.",
  zoom: "Scale the source inside the canvas.",
  panX: "Move the source left or right.",
  panY: "Move the source up or down.",

  cellWidth: "Set each grid cell's width in pixels.",
  cellHeight: "Set each grid cell's height in pixels.",
  gapX: "Set horizontal space between cells.",
  gapY: "Set vertical space between cells.",
  cornerRadius: "Round the corners of stripe cells.",
  orientation: "Choose whether stripes run vertically or horizontally.",
  letterSize: "Set the letter font size.",
  letterRatio: "Control how many eligible cells show letters.",
  letterCharset: "Choose which characters can appear.",
  letterColor: "Set the letter color.",
  letterShuffleSpeed: "Control how quickly letters change.",
  gapPeriodMin: "Set the shortest gap sparkle duration.",
  gapPeriodMax: "Set the longest gap sparkle duration.",
  widthPeriodMin: "Set the shortest width shuffle duration.",
  widthPeriodMax: "Set the longest width shuffle duration.",
  widthSwing: "Set how far stripe widths can shift.",
  colorSmoothing: "Limit how quickly stripe colors can change.",
  updateInterval: "Set how often the grid animation updates.",
} as const;
