import path from "node:path";
import type { LottieSvg } from "../../../src/components/_animations/products/lottie-svg/types";

const root = process.cwd();

export const DEFAULT_LOTTIE_DIR = path.join(
  root,
  "src/components/_animations/products/lottie"
);

export const DEFAULT_CSS_PATH = path.join(root, "src/styles/_colors.css");

export const DEFAULT_OUT_PATH = path.join(
  root,
  "src/components/_animations/products/lottie-svg/lottie-svg.gen.ts"
);

export type Registry = Record<string, LottieSvg>;

export function renderRegistry(registry: Registry): string {
  const sorted: Registry = {};
  for (const name of Object.keys(registry).sort()) {
    sorted[name] = registry[name];
  }

  return `// AUTO-GENERATED by dev/vite/lottie-svg — do not edit. Run \`pnpm run lottie-svg:gen\` to regenerate.
import type { IconName } from "@/components/icon/icons.gen";
import type { LottieSvg } from "./types";

export const LOTTIE_SVG_ICONS = ${JSON.stringify(sorted)} satisfies Partial<
  Record<IconName, LottieSvg>
>;

export type LottieSvgIconName = keyof typeof LOTTIE_SVG_ICONS;

export function hasLottieSvgIcon(name: IconName): name is LottieSvgIconName {
  return name in LOTTIE_SVG_ICONS;
}
`;
}
