import { normalizeEngineConfig } from "@necatikcl/stripes-engine";

export const DEFAULT_LAB_ENGINE_CONFIG = normalizeEngineConfig({
  transform: {
    fit: "stretch",
    zoom: 1,
    panX: 0,
    panY: 0,
  },
  adjustments: {
    brightness: 0,
    exposure: 0,
    contrast: 1,
    blackPoint: 0,
    whitePoint: 1,
    gamma: 1,
    invert: false,
    posterizeLevels: 0,
    thresholdBias: 0,
    noiseAmount: 0,
    blurRadius: 0,
    sharpenAmount: 0,
  },
  background: {
    color: 16015393,
    transparent: false,
    gradient: {
      enabled: false,
      direction: "topToBottom",
      stopCount: 2,
      stops: [16777215, 0, 0, 0],
    },
    grid: {
      enabled: false,
      cellWidth: 96,
      cellHeight: 96,
      gapX: 8,
      gapY: 8,
      cornerRadius: 0,
      color: 15987699,
      opacity: 1,
    },
    stars: {
      enabled: true,
      density: 10,
      sizePx: 16,
      sizeRandomness: 1,
      tiltAngleDeg: -15,
      twinkleSpeed: 1,
      twinkleAmount: 0.7,
      opacity: 1,
      color: 16777215,
    },
  },
  grid: {
    cellWidth: 7,
    cellHeight: 7,
    gapX: 0,
    gapY: 0,
    cornerRadius: 0,
    orientation: "vertical",
    angleDeg: 0,
    rotationMode: "cell",
  },
  stripes: [
    {
      color: 16410152,
      startFrom: 0,
      width: 0.5,
      opacity: 1,
    },
    {
      color: 16738845,
      startFrom: 0.0259,
      width: 1,
      opacity: 1,
    },
    {
      color: 16741916,
      startFrom: 0.0978,
      width: 1.5,
      opacity: 1,
    },
    {
      color: 16746538,
      startFrom: 0.2084,
      width: 2,
      opacity: 1,
    },
    {
      color: 16751421,
      startFrom: 0.3514,
      width: 2.5,
      opacity: 1,
    },
    {
      color: 16756048,
      startFrom: 0.5214,
      width: 3,
      opacity: 1,
    },
    {
      color: 16759650,
      startFrom: 0.7109,
      width: 3.5,
      opacity: 1,
    },
    {
      color: 16761969,
      startFrom: 0.9,
      width: 4,
      opacity: 1,
    },
  ],
  stripesEnabled: true,
  fieldScale: 1,
  reveal: {
    enabled: false,
    type: "wave",
    wave: {
      position: "center",
      durationMs: 1200,
      softness: 0.22,
      waviness: 0.11,
    },
    assembly: {
      sliceSizePx: 40,
      speedMinMs: 300,
      speedMaxMs: 1600,
      staggerMs: 900,
      scatterPx: 50,
      angleJitterDeg: 22,
    },
  },
  sparkle: {
    gaps: {
      enabled: false,
      coverage: 0.22,
      speed: 1,
    },
    width: {
      enabled: true,
      coverage: 0.3,
      swingPx: 1.25,
      swingPeriodMin: 0.5,
      swingPeriodMax: 1,
    },
    motion: {
      enabled: false,
      amplitudePx: 29,
      staggerPx: 218,
      maxOffsetPx: 63.5,
      speed: 2.45,
      direction: "rightToLeft",
    },
  },
  flames: {
    enabled: true,
    direction: "up",
    minWidthRatio: 0.01,
    maxWidthRatio: 0.03,
    minHeightRatio: 0.01,
    maxHeightRatio: 0.06,
    baseSpeedPxPerSec: 30,
    speedVariation: 1,
    spawnIntervalMs: 80,
    spawnJitterMs: 80,
    maxActive: 15,
    edgeSharpness: 1,
    opacityMin: 0.3,
    opacityMax: 1,
  },
  edgeMask: {
    enabled: true,
    start: 0,
    end: 0.1,
    power: 1,
  },
  cursorTrail: {
    enabled: true,
    particleRadius: 40,
    particleAlpha: 0.07,
    particleLifeMs: 960,
    particleLifeJitterMs: 100,
    emitterVelocitySmoothing: 0.7,
    particleVelocityScale: 0.01,
    particleTangentVelocity: 1.65,
    particleDamping: 0.96,
    particleSpacingPx: 3,
    maxEmitPerTick: 10,
    spreadMinPx: 1.5,
    spreadMaxPx: 21,
    spinStrength: 0.04,
    densityRadiusMinScale: 0.2,
    densityRadiusLifeScale: 1,
    pushRadiusScale: 0.9,
    pushStrengthPx: 48,
    pushLagPx: 0,
    pushWobblePx: 8,
    pushLeadBlackAlpha: 0,
  },
  clickWave: {
    enabled: true,
    lifeMs: 630,
    startRadiusPx: 6,
    maxRadiusPx: 120,
    startStrokeWidthPx: 24,
    endStrokeWidthPx: 12,
    maxWaves: 12,
    pushStrengthPx: 38,
    pushBandScale: 3.2,
    stripeWhiteAlpha: 0.5,
  },
  letters: {
    enabled: false,
    mode: "random",
    coverage: 0.1,
    positionX: 0.5,
    positionY: 0.5,
    areaWidth: 1,
    areaHeight: 1,
    text: "CF",
    textCopies: 1,
    fontFamily: "monospace",
    sizeScale: 0.9,
    shuffleSpeed: 1,
  },
  colors: {
    mode: "luminance",
    stripeBlendMode: "normal",
    autoDetectBackground: true,
    backgroundColor: 0,
    gradient: {
      direction: "topToBottom",
      stopCount: 2,
      stops: [16777215, 0, 0, 0],
    },
  },
  renderMode: "sharp",
  renderIntensity: 1,
  renderParams: [0.5, 0.5, 0.5, 0.5],
  renderColorA: 2236962,
  renderColorB: 16777215,
});

export const DEFAULT_LAB_UI_SETTINGS = {
  canvasMode: "scale",
  canvasScale: 1,
  canvasWidth: 1000,
  canvasHeight: 1000,
  exportStartSec: 0,
  exportDurationSec: 5,
  backgroundColor: 16015393,
  textureId: "cf-base",
  backgroundFillMode: "solid",
  stripePalette: "Background Ramp",
  backgroundRampEasing: "custom:0.373,0.048,0.558,1",
  thresholdDistributionEasing: "custom:0.42,0,0.842,0.797",
  autoStripeWidths: true,
  drawerOpen: {
    Background: true,
    "Background Stars": false,
    Stripes: true,
    "Background Flames": false,
    General: true,
    "Click Wave": false,
    "Cursor Trail": false,
    "Edge Mask": false,
    Letters: false,
    Sparkle: false,
    Colors: false,
    "Texture Tone": false,
    "Texture Levels": false,
    "Texture Source": false,
    Reveal: true,
  },
} as const;
