import { DEFAULT_ENGINE_CONFIG, normalizeEngineConfig, sanitizeThemedConfig } from "@necatikcl/stripes-engine";
import type { DeepPartial, EngineConfig } from "@necatikcl/stripes-engine";
import factoryDefaults from "./factoryDefaults.json";
import { COMET_LOGO_DEFAULTS } from "@necatikcl/stripes-engine";

type PlainRecord = Record<string, unknown>;

function isPlainObject(value: unknown): value is PlainRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function deepMergeDefaults<T>(base: T, override: unknown): T {
  if (Array.isArray(override)) return override as T;
  if (!isPlainObject(override)) return override === undefined ? base : (override as T);
  if (!isPlainObject(base)) return override as unknown as T;
  const merged: PlainRecord = { ...(base as PlainRecord) };
  for (const key of Object.keys(override)) {
    const value = override[key];
    if (value === undefined) continue;
    merged[key] = deepMergeDefaults((base as PlainRecord)[key], value);
  }
  return merged as unknown as T;
}

const HAND_WRITTEN_ENGINE_CONFIG: Partial<EngineConfig> = {
  transform: {
    fit: "width",
    zoom: 1,
    panX: 0,
    panY: 0,
  },
  adjustments: {
    brightness: -0.07,
    exposure: -0.05,
    contrast: 0.8,
    blackPoint: 0,
    whitePoint: 1,
    gamma: 1.15,
    invert: false,
    posterizeLevels: 0,
    thresholdBias: 0,
    noiseAmount: 0,
    blurRadius: 0,
    sharpenAmount: 0,
  },
  background: {
    color: 16777215,
    transparent: false,
    gradient: {
      enabled: false,
      direction: "topToBottom",
      stopCount: 2,
      stops: [16777215, 0, 0, 0],
      hueDriftDeg: 0,
      saturationBoost: 0,
    },
    grid: {
      enabled: false,
      cellWidth: 32,
      cellHeight: 32,
      gapX: 4,
      gapY: 4,
      cornerRadius: 0,
      color: 15987699,
      opacity: 1,
    },
    stars: {
      enabled: false,
      density: 10,
      sizePx: 4,
      sizeRandomness: 1,
      tiltAngleDeg: -15,
      twinkleSpeed: 1,
      twinkleAmount: 0.7,
      opacity: 0.71,
      color: 16777215,
    },
    meteors: { ...DEFAULT_ENGINE_CONFIG.background.meteors },
  },
  grid: {
    cellWidth: 7,
    cellHeight: 7,
    gapX: 0,
    gapY: 0,
    cornerRadius: 0,
    orientation: "vertical",
    angleDeg: 36,
    rotationMode: "overlap",
    overlapAmount: 4,
    streamGapWave: { enabled: false, squeeze: 0, wavelengthCells: 16, speed: 0, phaseDeg: 0 },
  },
  stripes: [
    {
      color: 16738081, // #ff6721 Orange 700 main
      startFrom: 0,
      width: 0.5,
      opacity: 1,
    },
    {
      color: 16431163, // #fab83b Orange 650 specialty
      startFrom: 0.1389,
      width: 1,
      opacity: 1,
    },
    {
      color: 16153662, // #f67c3e Orange 600
      startFrom: 0.2736,
      width: 1.5,
      opacity: 1,
    },
    {
      color: 16686156, // #fe9c4c Orange 500
      startFrom: 0.4,
      width: 2,
      opacity: 1,
    },
    {
      color: 16759152, // #ffb970 Orange 400
      startFrom: 0.5142,
      width: 2.5,
      opacity: 1,
    },
    {
      color: 16765589, // #ffd295 Orange 300
      startFrom: 0.6128,
      width: 3,
      opacity: 1,
    },
    {
      color: 16769973, // #ffe3b5 Orange 200
      startFrom: 0.6928,
      width: 3.5,
      opacity: 1,
    },
    {
      color: 16707538, // #feefd2 Orange 100
      startFrom: 0.7518,
      width: 4,
      opacity: 1,
    },
    {
      color: 16775400, // #fff8e8 Orange 0
      startFrom: 0.7878,
      width: 4.5,
      opacity: 1,
    },
    {
      color: 16448250, // #fafafa
      startFrom: 0.8,
      width: 5,
      opacity: 1,
    },
  ],
  stripesEnabled: true,
  fieldScale: 2,
  reveal: {
    enabled: true,
    type: "wave",
    wave: {
      position: "center",
      durationMs: 1200,
      softness: 0.22,
      waviness: 0.11,
    },
    assembly: {
      sliceSizePx: 40,
      speedMinMs: 300,
      speedMaxMs: 1600,
      staggerMs: 900,
      scatterPx: 50,
      angleJitterDeg: 22,
      blurPx: 17.5,
      blurStart: 0.45,
    },
    turbulence: { speedMinMs: 400, speedMaxMs: 2600, staggerMs: 1400, intensity: 1, detail: 0.5, glow: 0.6 },
    glitch: { speedMinMs: 200, speedMaxMs: 1400, staggerMs: 1200, intensity: 1, detail: 0.5, glow: 0.8 },
    vortex: {
      speedMinMs: 300,
      speedMaxMs: 1400,
      staggerMs: 2600,
      intensity: 1,
      detail: 0.5,
      glow: 0.7,
      swirl: 1,
    },
    blackhole: {
      speedMinMs: 260,
      speedMaxMs: 1050,
      staggerMs: 3600,
      intensity: 1,
      detail: 0.5,
      glow: 0.7,
      swirl: 1.2,
      formMs: 1150,
      collapseMs: 420,
      arms: 3,
      lensing: 1,
      horizon: 0.12,
    },
    whirlpool: {
      durationMs: 5600,
      turns: 4,
      tightness: 0.22,
      streak: 0.6,
      glow: 0.4,
    },
    water: {
      durationMs: 950,
      settleMs: 520,
      rows: 5,
      intensity: 1.7,
      wobble: 0.7,
      refraction: 1.3,
      softness: 0.35,
    },
  },
  sparkle: {
    gaps: {
      enabled: false,
      coverage: 0.22,
      speed: 1,
    },
    width: {
      enabled: true,
      coverage: 0.3,
      swingPx: 1.25,
      swingPeriodMin: 0.5,
      swingPeriodMax: 1,
    },
    stripe: {
      enabled: true,
      coverage: 0.48,
      maxBrightness: 0.5,
      speed: 0.4,
      thickestCount: 4,
      hueDriftDeg: 12.5,
      saturationBoost: 0.3,
    },
    motion: {
      enabled: false,
      amplitudePx: 29,
      staggerPx: 218,
      maxOffsetPx: 63.5,
      speed: 2.45,
      direction: "rightToLeft",
    },
  },
  flames: {
    enabled: true,
    direction: "up",
    minWidthRatio: 0.01,
    maxWidthRatio: 0.03,
    minHeightRatio: 0.01,
    maxHeightRatio: 0.06,
    baseSpeedPxPerSec: 30,
    speedVariation: 1,
    spawnIntervalMs: 80,
    spawnJitterMs: 80,
    maxActive: 15,
    edgeSharpness: 1,
    opacityMin: 0.3,
    opacityMax: 0.6,
    vortexSingular: {
      segCount: 22,
      segSpacingPx: 10,
      turnRate: 0.9,
      turnVariation: 0.8,
      visibleMinMs: 7000,
      visibleMaxMs: 13000,
      hiddenMinMs: 800,
      hiddenMaxMs: 2600,
      lifeMinMs: 12000,
      lifeMaxMs: 24000,
      edgeMarginRatio: 0.12,
    },
  },
  edgeMask: {
    enabled: false,
    start: 0.075,
    end: 0.5,
    power: 0.2,
    sides: { top: true, right: true, bottom: true, left: true },
  },
  cursorTrail: {
    enabled: true,
    type: "default",
    particleRadius: 40,
    particleAlpha: 0.07,
    particleLifeMs: 960,
    particleLifeJitterMs: 100,
    emitterVelocitySmoothing: 0.7,
    particleVelocityScale: 0.01,
    particleTangentVelocity: 1.65,
    particleDamping: 0.96,
    particleSpacingPx: 3,
    maxEmitPerTick: 10,
    spreadMinPx: 1.5,
    spreadMaxPx: 21,
    spinStrength: 0.04,
    densityRadiusMinScale: 0.2,
    densityRadiusLifeScale: 1,
    pushRadiusScale: 0.9,
    pushStrengthPx: 48,
    pushLagPx: 0,
    pushWobblePx: 8,
    pushLeadBlackAlpha: 0,
    constellation: { ...DEFAULT_ENGINE_CONFIG.cursorTrail.constellation },
    comet: { ...DEFAULT_ENGINE_CONFIG.cursorTrail.comet },
  },
  clickWave: {
    enabled: true,
    type: "default",
    lifeMs: 630,
    startRadiusPx: 6,
    maxRadiusPx: 120,
    startStrokeWidthPx: 24,
    endStrokeWidthPx: 12,
    maxWaves: 12,
    pushStrengthPx: 38,
    pushBandScale: 3.2,
    stripeWhiteAlpha: 0.5,
    detonation: { ...DEFAULT_ENGINE_CONFIG.clickWave.detonation },
  },
  letters: {
    enabled: false,
    mode: "random",
    colorMode: "white",
    color: 16777215,
    coverage: 0.1,
    positionX: 0.5,
    positionY: 0.5,
    areaWidth: 1,
    areaHeight: 1,
    text: "CF",
    textCopies: 1,
    fontFamily: "Geist Mono Medium",
    sizeScale: 0.9,
    shuffleSpeed: 1,
  },
  colors: {
    mode: "luminance",
    stripeBlendMode: "normal",
    imageColorLightness: 0,
    imageColorDensity: 1,
    imageColorRemoveThin: 0,
    imageColorBoostThick: 0,
    autoDetectBackground: false,
    backgroundColor: 0,
    gradient: {
      enabled: false,
      direction: "topToBottom",
      stopCount: 2,
      stops: [16777215, 0, 0, 0],
      hueDriftDeg: 0,
      saturationBoost: 0,
    },
  },
  renderMode: "sharp",
  renderIntensity: 1,
  renderParams: [0.5, 0.5, 0.5, 0.5],
  renderColorA: 2236962,
  renderColorB: 16777215,
};

const { dark: FACTORY_DEFAULT_DARK, ...FACTORY_DEFAULT_LIGHT } = factoryDefaults.config;
const NORMALIZED_FACTORY_DEFAULT_LIGHT = normalizeEngineConfig(
  deepMergeDefaults(HAND_WRITTEN_ENGINE_CONFIG, FACTORY_DEFAULT_LIGHT),
);

export const DEFAULT_LAB_ENGINE_CONFIG = sanitizeThemedConfig({
  ...NORMALIZED_FACTORY_DEFAULT_LIGHT,
  ...(FACTORY_DEFAULT_DARK ? { dark: FACTORY_DEFAULT_DARK as DeepPartial<EngineConfig> } : {}),
}) as EngineConfig & { dark?: DeepPartial<EngineConfig> };

const HAND_WRITTEN_LAB_UI_SETTINGS = {
  canvasMode: "scale",
  canvasScale: 1,
  canvasWidth: 800,
  canvasHeight: 400,
  canvasAspectLocked: true,
  exportStartSec: 0,
  exportDurationSec: 5,
  exportSvgIncludeBackground: false,
  backgroundColor: 16777215,
  textureId: "cf-base",
  textureSourceMode: "shader",
  shaderSourceCode:
    '// "Supernova remnant" by Duke\n// https://www.shadertoy.com/view/MdKXzc\n//-------------------------------------------------------------------------------------\n// Based on "Dusty nebula 4" (https://www.shadertoy.com/view/MsVXWW) \n// and "Protoplanetary disk" (https://www.shadertoy.com/view/MdtGRl) \n// otaviogood\'s "Alien Beacon" (https://www.shadertoy.com/view/ld2SzK)\n// and Shane\'s "Cheap Cloud Flythrough" (https://www.shadertoy.com/view/Xsc3R4) shaders\n// Some ideas came from other shaders from this wonderful site\n// Press 1-2-3 to zoom in and zoom out.\n// License: Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License\n//-------------------------------------------------------------------------------------\n\n#define DITHERING\n#define BACKGROUND\n\n//#define TONEMAPPING\n\n//-------------------\n#define R(p, a) p=cos(a)*p+sin(a)*vec2(p.y, -p.x)\n\n// iq\'s noise\nfloat noise( in vec3 x )\n{\n    vec3 p = floor(x);\n    vec3 f = fract(x);\n\tf = f*f*(3.0-2.0*f);\n\tvec2 uv = (p.xy+vec2(37.0,17.0)*p.z) + f.xy;\n\tvec2 rg = textureLod( iChannel0, (uv+ 0.5)/256.0, 0.0 ).yx;\n\treturn 1. - 0.82*mix( rg.x, rg.y, f.z );\n}\n\nfloat fbm(vec3 p)\n{\n   return noise(p*.06125)*.5 + noise(p*.125)*.25 + noise(p*.25)*.125 + noise(p*.4)*.2;\n}\n\nfloat length2( vec2 p )\n{\n\treturn sqrt( p.x*p.x + p.y*p.y );\n}\n\nfloat length8( vec2 p )\n{\n\tp = p*p; p = p*p; p = p*p;\n\treturn pow( p.x + p.y, 1.0/8.0 );\n}\n\n\nfloat Disk( vec3 p, vec3 t )\n{\n    vec2 q = vec2(length2(p.xy)-t.x,p.z*0.5);\n    return max(length8(q)-t.y, abs(p.z) - t.z);\n}\n\n//==============================================================\n// otaviogood\'s noise from https://www.shadertoy.com/view/ld2SzK\n//--------------------------------------------------------------\n// This spiral noise works by successively adding and rotating sin waves while increasing frequency.\n// It should work the same on all computers since it\'s not based on a hash function like some other noises.\n// It can be much faster than other noise functions if you\'re ok with some repetition.\nconst float nudge = 0.9;\t// size of perpendicular vector\nconst float normalizer = 0.7432941462471664;\t// 1.0 / sqrt(1.0 + nudge*nudge)\nfloat SpiralNoiseC(vec3 p)\n{\n    float n = 0.0;\t// noise amount\n    float iter = 2.0;\n    for (int i = 0; i < 8; i++)\n    {\n        // add sin and cos scaled inverse with the frequency\n        n += -abs(sin(p.y*iter) + cos(p.x*iter)) / iter;\t// abs for a ridged look\n        // rotate by adding perpendicular and scaling down\n        p.xy += vec2(p.y, -p.x) * nudge;\n        p.xy *= normalizer;\n        // rotate on other axis\n        p.xz += vec2(p.z, -p.x) * nudge;\n        p.xz *= normalizer;\n        // increase the frequency\n        iter *= 1.733733;\n    }\n    return n;\n}\n\nfloat NebulaNoise(vec3 p)\n{\n    float final = Disk(p.xzy,vec3(2.0,1.8,1.25));\n    final += fbm(p*90.);\n    final += SpiralNoiseC(p.zxy*0.5123+100.0)*3.0;\n\n    return final;\n}\n\nfloat map(vec3 p) \n{\n\tR(p.xz, iMouse.x*0.008*pi+iTime*0.1);\n\n\tfloat NebNoise = abs(NebulaNoise(p/0.5)*0.5);\n    \n\treturn NebNoise+0.07;\n}\n//--------------------------------------------------------------\n\n// assign color to the media\nvec3 computeColor( float density, float radius )\n{\n\t// color based on density alone, gives impression of occlusion within\n\t// the media\n\tvec3 result = mix( vec3(1.0,0.9,0.8), vec3(0.4,0.15,0.1), density );\n\t\n\t// color added to the media\n\tvec3 colCenter = 7.*vec3(0.8,1.0,1.0);\n\tvec3 colEdge = 1.5*vec3(0.48,0.53,0.5);\n\tresult *= mix( colCenter, colEdge, min( (radius+.05)/.9, 1.15 ) );\n\t\n\treturn result;\n}\n\nbool RaySphereIntersect(vec3 org, vec3 dir, out float near, out float far)\n{\n\tfloat b = dot(dir, org);\n\tfloat c = dot(org, org) - 8.;\n\tfloat delta = b*b - c;\n\tif( delta < 0.0) \n\t\treturn false;\n\tfloat deltasqrt = sqrt(delta);\n\tnear = -b - deltasqrt;\n\tfar = -b + deltasqrt;\n\treturn far > 0.0;\n}\n\n// Applies the filmic curve from John Hable\'s presentation\n// More details at : http://filmicgames.com/archives/75\nvec3 ToneMapFilmicALU(vec3 _color)\n{\n\t_color = max(vec3(0), _color - vec3(0.004));\n\t_color = (_color * (6.2*_color + vec3(0.5))) / (_color * (6.2 * _color + vec3(1.7)) + vec3(0.06));\n\treturn _color;\n}\n\nvoid mainImage( out vec4 fragColor, in vec2 fragCoord )\n{  \n    const float KEY_1 = 49.5/256.0;\n\tconst float KEY_2 = 50.5/256.0;\n\tconst float KEY_3 = 51.5/256.0;\n    float key = 0.0;\n    key += 0.7*texture(iChannel1, vec2(KEY_1,0.25)).x;\n    key += 0.7*texture(iChannel1, vec2(KEY_2,0.25)).x;\n    key += 0.7*texture(iChannel1, vec2(KEY_3,0.25)).x;\n\n\t// ro: ray origin\n\t// rd: direction of the ray\n\tvec3 rd = normalize(vec3((fragCoord.xy-0.5*iResolution.xy)/iResolution.y, 1.));\n\tvec3 ro = vec3(0., 0., -6.+key*1.6);\n    \n\t// ld, td: local, total density \n\t// w: weighting factor\n\tfloat ld=0., td=0., w=0.;\n\n\t// t: length of the ray\n\t// d: distance function\n\tfloat d=1., t=0.;\n    \n    const float h = 0.1;\n   \n\tvec4 sum = vec4(0.0);\n   \n    float min_dist=0.0, max_dist=0.0;\n\n    if(RaySphereIntersect(ro, rd, min_dist, max_dist))\n    {\n       \n\tt = min_dist*step(t,min_dist);\n   \n\t// raymarch loop\n\tfor (int i=0; i<64; i++) \n\t{\n\t \n\t\tvec3 pos = ro + t*rd;\n  \n\t\t// Loop break conditions.\n\t    if(td>0.9 || d<0.1*t || t>10. || sum.a > 0.99 || t>max_dist) break;\n        \n        // evaluate distance function\n        float d = map(pos);\n\t\t       \n\t\t// change this string to control density \n\t\td = max(d,0.0);\n        \n        // point light calculations\n        vec3 ldst = vec3(0.0)-pos;\n        float lDist = max(length(ldst), 0.001);\n\n        // the color of light \n        vec3 lightColor=vec3(1.0,0.5,0.25);\n        \n        sum.rgb+=(vec3(0.67,0.75,1.00)/(lDist*lDist*10.)/80.); // star itself\n        sum.rgb+=(lightColor/exp(lDist*lDist*lDist*.08)/30.); // bloom\n        \n\t\tif (d<h) \n\t\t{\n\t\t\t// compute local density \n\t\t\tld = h - d;\n            \n            // compute weighting factor \n\t\t\tw = (1. - td) * ld;\n     \n\t\t\t// accumulate density\n\t\t\ttd += w + 1./200.;\n\t\t\n\t\t\tvec4 col = vec4( computeColor(td,lDist), td );\n            \n            // emission\n            sum += sum.a * vec4(sum.rgb, 0.0) * 0.2;\t\n            \n\t\t\t// uniform scale density\n\t\t\tcol.a *= 0.2;\n\t\t\t// colour by alpha\n\t\t\tcol.rgb *= col.a;\n\t\t\t// alpha blend in contribution\n\t\t\tsum = sum + col*(1.0 - sum.a);  \n       \n\t\t}\n      \n\t\ttd += 1./70.;\n\n        #ifdef DITHERING\n        //idea from https://www.shadertoy.com/view/lsj3Dw\n        vec2 uv = fragCoord.xy / iResolution.xy;\n        uv.y*=120.;\n        uv.x*=280.;\n        d=abs(d)*(.8+0.08*texture(iChannel2,vec2(uv.y,-uv.x+0.5*sin(4.*iTime+uv.y*4.0))).r);\n        #endif \n\t\t\n        // trying to optimize step size near the camera and near the light source\n        t += max(d * 0.1 * max(min(length(ldst),length(ro)),1.0), 0.01);\n        \n\t}\n    \n    // simple scattering\n\tsum *= 1. / exp( ld * 0.2 ) * 0.6;\n        \n   \tsum = clamp( sum, 0.0, 1.0 );\n   \n    sum.xyz = sum.xyz*sum.xyz*(3.0-2.0*sum.xyz);\n    \n\t}\n\n    #ifdef BACKGROUND\n    // stars background\n    if (td<.8)\n    {\n        vec3 stars = vec3(noise(rd*500.0)*0.5+0.5);\n        vec3 starbg = vec3(0.0);\n        starbg = mix(starbg, vec3(0.8,0.9,1.0), smoothstep(0.99, 1.0, stars)*clamp(dot(vec3(0.0),rd)+0.75,0.0,1.0));\n        starbg = clamp(starbg, 0.0, 1.0);\n        sum.xyz += starbg; \n    }\n\t#endif\n   \n    #ifdef TONEMAPPING\n    fragColor = vec4(ToneMapFilmicALU(sum.xyz*2.2),1.0);\n\t#else\n    fragColor = vec4(sum.xyz,1.0);\n\t#endif\n}',
  shaderSourceWidth: 1280,
  shaderSourceHeight: 960,
  twizzlerEnabled: true,
  twizzler: {
    color: "#f46021",
    colorFar: "#fea700",
    colorNear: "#f46021",
    colorEdge: "#e92e28",
    opacity: 1,
    scale: 1,
    centerY: 0.5,
    amplitude: 1,
    lineCount: 56,
    lineWidth: 1.15,
    pointSpacing: 10,
    leftHeight: 0.5,
    rightHeight: 0.5,
    edgeFluctuation: 0.12,
    edgeSpeed: 0.65,
    edgeTaper: 0.15,
    wrinkles: 3,
    wrinkleStrength: 0.09,
    bendPosition: 0.5,
    bendAmount: 0,
    bend2Position: 0.3,
    bend2Amount: 0,
    bend3Position: 0.75,
    bend3Amount: 0,
    depthPosition: 0.65,
    depthAmount: 0,
    depthWidth: 0.25,
    depth2Position: 0.35,
    depth2Amount: 0,
    depth2Width: 0.25,
    depthSpread: 0,
    depthLift: 0,
    depthTerrain: 0,
    twist: 1.15,
    rotateXDeg: 12,
    rotateYDeg: -18,
    rotateZDeg: 0,
    fov: 1.05,
    camDist: 10.5,
    perspectiveWidth: 1.8,
    minLineWidth: 0.4,
    maxLineWidth: 3.2,
    gradientsEnabled: true,
    ribbonColorMode: "baked",
    gradientXEnabled: true,
    gradientXMix: 1,
    gradientYEnabled: true,
    gradientYMix: 0.85,
    gradientZEnabled: true,
    gradientZStrength: 0.75,
    gradientZCenter: 0,
    gradientZWidth: 0.95,
    backgroundColor: "#ffffff",
    noiseScaleX: 0.0015,
    noiseScaleY: 0.012,
    speed: 1,
    drift: 0.31,
    stippleSize: 0,
    stippleGap: 0.8,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
    panX: 0,
    panY: 0,
    panZ: 0,
    viewDistance: 30,
  },
  twizzlerMap: {
    backgroundLevel: 0.08,
    ribbonLevel: 0.52,
    shoulderLevel: 0.02,
    shoulderWidth: 7,
    topOffsetPx: 0,
    bottomOffsetPx: 0,
    topSpread: 1,
    bottomSpread: 1,
    flowEnabled: true,
    flowDirection: "topRightToBottomLeft",
    flowAmplitude: 0.2,
    flowSpeed: 0.8,
    flowSpacing: 0.16,
    flowBandWidth: 0.035,
    flowSoftness: 0.35,
    flowOpacity: 0.45,
    flowPhase: 0,
  },
  cometLogo: COMET_LOGO_DEFAULTS,
  backgroundFillMode: "solid",
  backgroundSourceOpacity: 0,
  stripePalette: "Orange",
  backgroundRampEasing: "easeOut",
  backgroundRampSettings: {
    brightnessAdd: 26,
    hueDriftDeg: 12.5,
    saturationBoost: 30,
    maxLightnessUnder20: 100,
    maxLightness20To40: 100,
    maxLightness40To60: 100,
    maxLightness60To70: 95,
    maxLightness70To80: 93,
    maxLightnessOver80: 93,
  },
  thresholdDistributionEasing: "easeOutSine",
  autoStripeWidths: false,
  drawerOpen: {
    "Background Flames": false,
    "Background Stars": false,
    "Background Meteors": false,
    "Texture Source": false,
    "Texture Tone": false,
    "Texture Levels": false,
    General: true,
    Background: false,
    Stripes: false,
    "Cursor Trail": false,
    "Click Wave": false,
    Letters: false,
    "Edge Mask": false,
    Colors: false,
    Grid: false,
    Camera: true,
    "Connect Wave": false,
    "Connect Shape": true,
    "Connect Fill": true,
    "Connect Colors": false,
  },
  previewZoom: null,
  textureSidebarOpen: true,
  shaderSidebarOpen: true,
  textureSidebarWidth: 272,
  shaderSidebarWidth: 272,
  connectShapeType: "spiral",
  shaderPresetId: "connect",
  connectCameraDistance: 60,
  connectCameraRotateX: -14.922460937499977,
  connectCameraRotateY: -180,
  connectCameraRotateZ: 77,
  connectCameraPanX: 4.75,
  connectCameraPanY: 4.25,
  connectCameraFov: 43,
  connectGradientUnderlay: true,
  shaderViewDistance: 30,
  shaderViewRotateX: 0,
  shaderViewRotateY: 0,
  shaderViewRotateZ: 0,
  shaderViewPanX: 0,
  shaderViewPanY: 0,
  shaderViewFov: 55,
  connectShaderParams: {
    speed: 0.15,
    shapeWidth: 21.5,
    twistX: 0.35,
    twistY: 0.35,
    shapeRadius: 10,
    shapeConeRadiusStart: 14,
    shapeConeRadiusEnd: 0.75,
    shapeTube: 3.5,
    shapeBend: 160,
    shapePitch: 28,
    shapeAmplitude: 6,
    shapeTurns: 1,
    shapeWaveFreq: 2,
    cylinderLength: 208,
    wavesX: 3,
    wavesY: 3,
    displacementHeight: 3.4,
    speedX: 0.025,
    speedY: 0.13,
    fillColor: "#ff7a1f",
    fillColor2: "#ffaf36",
    fillGradScale: 0.2,
    fillAlpha: 1,
    fillLow: 0.04,
    fillHigh: 0.88,
    fillRadius: 0,
    lineColor: "#e8481c",
    lineCount: 1186,
    lineWidth: 1,
    lineAlpha: 0.8,
    lineFadeLow: 0.35,
    lineFadeHigh: 0.72,
    hatchAngle: 90,
    hatchLift: 1.4,
    hatchSpacing: 0.22,
    hatchCell: 0.85,
    hatchFill: 0.22,
    dashMin: 0.15,
    dashMax: 0.95,
    hatchDensity: 8,
    densityFloor: 1,
    hatchDrift: 40,
    waveGate: 0.55,
    envCenter: 0.7,
    envSlope: 0.35,
    envWidth: 0.2,
    emitCount: 12000,
    emitAmount: 0.81,
    emitSpeed: 0.65,
    emitDist: 8,
    emitFall: 16,
    emitSize: 1,
    emitStretch: 13.9,
    emitAlpha: 0.95,
    emitPaleColor: "#ffe3d1",
    emitSalmonColor: "#ffb98c",
    emitOrangeColor: "#ff7a1f",
    emitAmberColor: "#ffa51f",
    emitDeepColor: "#e85d04",
    paleColor: "#ffe3d1",
    salmonColor: "#ffb98c",
    orangeColor: "#ff7a1f",
    amberColor: "#ffa51f",
    deepColor: "#e85d04",
    renderDpr: 1.75,
    shapeMeshQuality: 1,
    renderAntialias: true,
  },
} as const;

export const DEFAULT_LAB_UI_SETTINGS = deepMergeDefaults(HAND_WRITTEN_LAB_UI_SETTINGS, factoryDefaults.lab);
