import entries from "./rain-shader-library.json";

/**
 * Snapshot of the lab's GLSL shader library for the agenda rain's texture
 * source picker. Generated by `scripts/sync-rain-shader-library.mjs` — edit
 * shaders in the lab, then re-run the script; do not hand-edit the JSON.
 *
 * The default ("Wave to Full Screen") is inlined in `rain-texture-source.ts`,
 * so the overlay only pulls this module in when another preset is picked.
 */

export type RainShaderLibraryEntry = {
  id: string;
  label: string;
  source: string;
};

export const RAIN_SHADER_LIBRARY = entries as RainShaderLibraryEntry[];

/** Matches the lab's `GRAPHIC_RAIN_SHADER_PRESET_ID` ("Wave to Full Screen"). */
export const DEFAULT_RAIN_SHADER_ID = "a1f684cd-6845-4f12-8978-e8315cfb4820";

export function findRainShaderSource(id: string): string | null {
  return RAIN_SHADER_LIBRARY.find((entry) => entry.id === id)?.source ?? null;
}

/** Leva dropdown options: label → id. */
export function rainShaderOptions(): Record<string, string> {
  return Object.fromEntries(
    RAIN_SHADER_LIBRARY.map((entry) => [entry.label, entry.id])
  );
}
