import type { CatalogGroup, CatalogItem } from "@/components/catalog/types";

export const products = {
  browserRun: {
    iconName: "product-browser-run",
    label: "Browser Run",
    description: "Automated browsers",
    href: "/products/browser-rendering",
  },
  cloudflarePages: {
    iconName: "product-cloudflare-pages",
    label: "Cloudflare Pages",
    description: "Build & deploy frontend sites",
    href: "#",
  },
  containers: {
    iconName: "product-containers",
    label: "Containers",
    description: "Any language, anywhere",
    href: "/products/containers",
  },
  durableObjects: {
    iconName: "product-durable-objects",
    label: "Durable Objects",
    description: "Stateful compute",
    href: "/products/durable-objects",
  },
  emailService: {
    iconName: "product-email-service",
    label: "Email Service",
    description: "Send and receive email",
    href: "/products/email-service",
  },
  sandboxes: {
    iconName: "product-sandboxes",
    label: "Sandboxes",
    description: "Secure code execution",
    href: "/products/sandboxes",
  },
  workers: {
    iconName: "product-workers",
    label: "Workers",
    description: "Global serverless functions",
    href: "/products/workers",
    isNew: true,
  },
  workersForPlatforms: {
    iconName: "product-workers-for-platforms",
    label: "Workers for Platforms",
    description: "Programmable platform",
    href: "/products/workers-for-platforms",
  },
  workersObservability: {
    iconName: "product-workers-observability",
    label: "Workers Observability",
    description: "Observability for Workers",
    href: "#",
  },
  workflows: {
    iconName: "product-workflows",
    label: "Workflows",
    description: "Process orchestration",
    href: "/products/workflow",
  },
  artifacts: {
    iconName: "product-artifacts",
    label: "Artifacts",
    description: "Git-native versioned storage",
    href: "#",
  },
  cacheReserve: {
    iconName: "product-cache-reserve",
    label: "Cache Reserve",
    description: "Caching for static content",
    href: "#",
  },
  d1: {
    iconName: "product-d1",
    label: "D1",
    description: "Serverless SQL",
    href: "#",
  },
  dataPlatform: {
    iconName: "product-data-platform",
    label: "Data Platform",
    description: "Ingest, catalog & query",
    href: "#",
  },
  hyperdrive: {
    iconName: "product-hyperdrive",
    label: "Hyperdrive",
    description: "Global databases",
    href: "#",
  },
  kv: {
    iconName: "product-kv",
    label: "KV",
    description: "Ultra-fast key-value storage",
    href: "#",
  },
  queues: {
    iconName: "product-queues",
    label: "Queues",
    description: "Message processing",
    href: "#",
  },
  r2: {
    iconName: "product-r2",
    label: "R2",
    description: "Egress-free storage",
    href: "#",
  },
  agents: {
    iconName: "product-agents",
    label: "Agents",
    description: "Build stateful AI agents",
    href: "#",
  },
  aiGateway: {
    iconName: "product-ai-gateway",
    label: "AI Gateway",
    description: "AI observability",
    href: "#",
  },
  aiSearch: {
    iconName: "product-ai-search",
    label: "AI Search",
    description: "Instant retrieval",
    href: "#",
  },
  vectorize: {
    iconName: "product-vectorize",
    label: "Vectorize",
    description: "Vector database",
    href: "#",
  },
  web3: {
    iconName: "product-web3",
    label: "Web3",
    description: "Web3 Infrastructure",
    href: "#",
  },
  workersAi: {
    iconName: "product-workers-ai",
    label: "Workers AI",
    description: "Edge AI models",
    href: "#",
  },
  images: {
    iconName: "product-images",
    label: "Images",
    description: "Image optimization",
    href: "#",
  },
  realtimeKit: {
    iconName: "product-realtimekit",
    label: "RealtimeKit",
    description: "Live comms",
    href: "#",
  },
  stream: {
    iconName: "product-stream",
    label: "Stream",
    description: "Video streaming",
    href: "#",
  },
  turnSfu: {
    iconName: "product-turn-sfu",
    label: "TURN / SFU",
    description: "Real-time infra",
    href: "#",
  },
  webAnalytics: {
    iconName: "product-analytics",
    label: "Analytics",
    description: "Web performance & security",
    href: "#",
  },
  botManagement: {
    iconName: "product-bot-management",
    label: "Bot Management",
    description: "Block bad bots",
    href: "#",
  },
  pageShield: {
    iconName: "product-page-shield",
    label: "Page Shield",
    description: "Client-Side protection",
    href: "#",
  },
  ddosProtection: {
    iconName: "product-ddos-protection",
    label: "DDoS Protection",
    description: "Mitigation solutions",
    href: "#",
  },
  magicTransit: {
    iconName: "product-magic-transit",
    label: "Magic Transit",
    description: "DDoS protection for networks",
    href: "#",
  },
  networkFirewall: {
    iconName: "product-network-firewall",
    label: "Network Firewall",
    description: "Firewall for enterprise WAN",
    href: "#",
  },
  rateLimiting: {
    iconName: "product-rate-limiting",
    label: "Rate Limiting",
    description: "Abuse prevention",
    href: "#",
  },
  ssl: {
    iconName: "product-ssl",
    label: "SSL",
    description: "Secure your site with SSL",
    href: "#",
  },
  turnstile: {
    iconName: "product-turnstile",
    label: "Turnstile",
    description: "A CAPTCHA replacement",
    href: "#",
  },
  waf: {
    iconName: "product-waf",
    label: "WAF",
    description: "Web application firewall",
    href: "#",
  },
  cdn: {
    iconName: "product-cdn",
    label: "CDN",
    description: "Faster delivery & caching",
    href: "#",
  },
  cloudflareWan: {
    iconName: "product-wan",
    label: "WAN",
    description: "Cloud-delivered networking",
    href: "#",
  },
  dns: {
    iconName: "product-dns",
    label: "DNS",
    description: "Fast DNS",
    href: "#",
  },
  loadBalancing: {
    iconName: "product-load-balancing",
    label: "Load Balancing",
    description: "Zero downtime",
    href: "#",
  },
  mesh: {
    iconName: "product-mesh",
    label: "Mesh",
    description: "Agents private network",
    href: "#",
  },
  networkInterconnect: {
    iconName: "product-network-interconnect",
    label: "Network Interconnect",
    description: "Direct interconnections",
    href: "#",
  },
  sase: {
    iconName: "product-sase",
    label: "SASE",
    description: "Cloudflare SASE platform",
    href: "#",
  },
  zeroTrustNetworkAccess: {
    iconName: "product-access",
    label: "Access",
    description: "Safe access to private apps",
    href: "#",
  },
  secureWebGateway: {
    iconName: "product-secure-web-gateway",
    label: "Secure Web Gateway",
    description: "DNS filtering & Secure",
    href: "#",
  },
  casb: {
    iconName: "product-sase",
    label: "Cloud Access Security Broker",
    description: "Protect data in SaaS apps",
    href: "#",
  },
  dataLossPrevention: {
    iconName: "product-data-loss-prevention",
    label: "Data Loss Prevention",
    description: "Protect sensitive data",
    href: "#",
  },
  firewallAsAService: {
    iconName: "product-waf",
    label: "Firewall-as-a-Service",
    description: "Network security enforcement",
    href: "#",
  },
  emailSecurity: {
    iconName: "product-email-security",
    label: "Email Security",
    description: "AI-driven Email Protection",
    href: "#",
  },
  remoteBrowserIsolation: {
    iconName: "product-browser-isolation",
    label: "Browser Isolation",
    description: "Protect users and data",
    href: "#",
  },
  digitalExperienceMonitoring: {
    iconName: "product-analytics",
    label: "Digital Experience Monitoring",
    description: "Pinpoint performance bottlenecks",
    href: "#",
  },
  advancedCertificateManager: {
    iconName: "product-advanced-certificate-manager",
    label: "Advanced Certificate Manager",
    description: "Lifecycle management",
    href: "#",
  },
  apiShield: {
    iconName: "product-api-shield",
    label: "API Shield",
    description: "API security & monitoring",
    href: "#",
  },
  argoSmartRouting: {
    iconName: "product-argo-smart-routing",
    label: "Argo Smart Routing",
    description: "Accelerate web apps",
    href: "#",
  },
  chinaNetwork: {
    iconName: "product-china-network",
    label: "China Network",
    description: "Web solutions in China",
    href: "#",
  },
  customDomainProtection: {
    iconName: "product-custom-domain-protection",
    label: "Custom Domain Protection",
    description: "Dedicated domain security",
    href: "#",
  },
  ddosForWeb: {
    iconName: "product-ddos-for-web",
    label: "DDoS for Web",
    description: "Website DDoS mitigation",
    href: "#",
  },
  emailRouting: {
    iconName: "product-email-routing",
    label: "Email Routing",
    description: "Manage custom email addresses with ease",
    href: "#",
  },
  keylessSsl: {
    iconName: "product-keyless-ssl",
    label: "Keyless SSL",
    description: "Secure SSL Control",
    href: "#",
  },
  logExplorer: {
    iconName: "product-log-explorer",
    label: "Log Explorer",
    description: "Observability and forensics",
    href: "#",
  },
  networkFlow: {
    iconName: "product-network-flow",
    label: "Network Flow",
    description: "Network traffic visibility",
    href: "#",
  },
  rdp: {
    iconName: "product-rdp",
    label: "RDP",
    description: "Remote desktop protection",
    href: "#",
  },
  spectrum: {
    iconName: "product-spectrum",
    label: "Spectrum",
    description: "DDoS protection TCP & UDP",
    href: "#",
  },
  spectrumForMinecraft: {
    iconName: "product-spectrum-for-minecraft",
    label: "Spectrum for Minecraft",
    description: "Minecraft server protection",
    href: "#",
  },
  waitingRoom: {
    iconName: "product-waiting-room",
    label: "Waiting Room",
    description: "Traffic management",
    href: "#",
  },
  aiSecurityForApps: {
    iconName: "product-ai-security-for-apps",
    label: "AI Security for Apps",
    description:
      "Protect your AI-powered applications with advanced security features",
    href: "#",
  },
  gateway: {
    iconName: "product-gateway",
    label: "Gateway",
    description: "Secure web gateway",
    href: "#",
  },
  clientSideSecurity: {
    iconName: "product-client-side-security",
    label: "Client-Side Security",
    description: "Client-Side Protection",
    href: "#",
  },
} satisfies Record<string, CatalogItem>;

const productGroups = {
  compute: {
    label: "Compute",
    slug: "compute",
    items: [
      products.browserRun,
      products.containers,
      products.durableObjects,
      products.sandboxes,
      products.workers,
      products.workersForPlatforms,
      products.workflows,
    ],
    secondaryItems: [
      products.cloudflarePages,
      products.emailService,
      products.workersObservability,
    ],
  },
  storage: {
    label: "Storage",
    slug: "storage",
    items: [
      products.artifacts,
      products.d1,
      products.dataPlatform,
      products.hyperdrive,
      products.kv,
      products.queues,
      products.r2,
    ],
    secondaryItems: [products.cacheReserve],
  },
  ai: {
    label: "AI",
    slug: "ai",
    items: [
      products.agents,
      products.aiGateway,
      products.aiSearch,
      products.vectorize,
      products.workersAi,
    ],
    secondaryItems: [products.web3],
  },
  media: {
    label: "Media",
    slug: "media",
    items: [products.images, products.realtimeKit, products.stream],
  },
  security: {
    label: "Security",
    slug: "security",
    items: [
      products.ddosProtection,
      products.magicTransit,
      products.rateLimiting,
      products.ssl,
      products.turnstile,
      products.waf,
    ],
    secondaryItems: [products.clientSideSecurity, products.networkFirewall],
  },
  network: {
    label: "Network",
    slug: "network",
    items: [
      products.webAnalytics,
      products.botManagement,
      products.cdn,
      products.dns,
      products.loadBalancing,
      products.pageShield,
      products.turnSfu,
    ],
    secondaryItems: [
      products.advancedCertificateManager,
      products.apiShield,
      products.argoSmartRouting,
      products.chinaNetwork,
      products.customDomainProtection,
      products.ddosForWeb,
      products.emailRouting,
      products.keylessSsl,
      products.logExplorer,
      products.networkFlow,
      products.networkInterconnect,
      products.rdp,
      products.spectrum,
      products.spectrumForMinecraft,
      products.waitingRoom,
    ],
  },
  saseZeroTrust: {
    label: "SASE / Zero Trust",
    slug: "sase-zero-trust",
    items: [
      products.sase,
      products.zeroTrustNetworkAccess,
      products.remoteBrowserIsolation,
      products.dataLossPrevention,
      products.emailSecurity,
      products.secureWebGateway,
      products.cloudflareWan,
    ],
    secondaryItems: [
      products.aiSecurityForApps,
      products.gateway,
      products.mesh,
    ],
  },
} satisfies Record<string, CatalogGroup>;

export const headerProductGroups: CatalogGroup[] = [
  productGroups.compute,
  productGroups.storage,
  productGroups.ai,
  productGroups.media,
  productGroups.security,
  productGroups.network,
  productGroups.saseZeroTrust,
];

export const sectionProductGroups: CatalogGroup[] = [
  productGroups.compute,
  productGroups.storage,
  productGroups.ai,
  productGroups.security,
  productGroups.network,
  productGroups.saseZeroTrust,
];

export const catalogProductGroups: CatalogGroup[] = [
  productGroups.compute,
  productGroups.storage,
  productGroups.ai,
  productGroups.media,
  productGroups.security,
  productGroups.network,
  productGroups.saseZeroTrust,
];
