import type { CommandMenuItem } from "./types";

export const commandMenuSuggestions = [
  {
    id: "home",
    label: "Home",
    description: "Platform homepage",
    href: "https://www.cloudflare.com/",
    iconName: "command-home",
    kind: "page",
  },
  {
    id: "products",
    label: "Products",
    description: "Explore products",
    href: "/products",
    iconName: "command-products",
    kind: "page",
  },
  {
    id: "pricing",
    label: "Pricing",
    description: "Plans and pricing",
    href: "https://www.cloudflare.com/plans/",
    iconName: "command-pricing",
    kind: "page",
  },
  {
    id: "solutions",
    label: "Solutions",
    description: "Explore solutions",
    href: "/solutions",
    iconName: "command-solutions",
    kind: "page",
  },
  {
    id: "resources",
    label: "Resources",
    description: "Guides, reports, and learning resources",
    href: "/resources",
    iconName: "command-resources",
    kind: "page",
  },
  {
    id: "learning",
    label: "Learning Center",
    description: "Learn about internet, security, and performance topics",
    href: "https://www.cloudflare.com/learning/",
    iconName: "command-learning-center",
    kind: "page",
  },
  {
    id: "case-studies",
    label: "Case Studies",
    description: "Customer stories and results",
    href: "/case-studies",
    iconName: "command-case-studies",
    kind: "page",
  },
  {
    id: "careers",
    label: "Careers",
    description: "Open roles and teams",
    href: "https://www.cloudflare.com/careers/",
    iconName: "command-careers",
    kind: "page",
  },
  {
    id: "partners",
    label: "Partners",
    description: "Cloudflare partner programs",
    href: "https://www.cloudflare.com/partners/",
    iconName: "command-partners",
    kind: "page",
  },
  {
    id: "press",
    label: "Press",
    description: "News, media resources, and company updates",
    href: "https://www.cloudflare.com/press/",
    iconName: "command-press",
    kind: "page",
  },
] satisfies readonly CommandMenuItem[];
