import type { EngineConfig } from "@necatikcl/stripes-engine";
import { drawerFolder } from "./drawerFolder";

export function buildEdgeMaskFolder(d: EngineConfig) {
  return drawerFolder("Edge Mask", {
    edgeMaskEnabled: { value: d.edgeMask.enabled, label: "Enabled" },
    edgeMaskStart: {
      value: d.edgeMask.start,
      min: 0,
      max: 0.5,
      step: 0.005,
      label: "Start inset",
      render: (get) => get("Edge Mask.edgeMaskEnabled") === true,
    },
    edgeMaskEnd: {
      value: d.edgeMask.end,
      min: 0,
      max: 0.5,
      step: 0.005,
      label: "End inset",
      render: (get) => get("Edge Mask.edgeMaskEnabled") === true,
    },
    edgeMaskPower: {
      value: d.edgeMask.power,
      min: 0.1,
      max: 4,
      step: 0.05,
      label: "Power",
      render: (get) => get("Edge Mask.edgeMaskEnabled") === true,
    },
  });
}

export function buildCursorTrailFolder(d: EngineConfig) {
  return drawerFolder("Cursor Trail", {
    cursorTrailEnabled: { value: d.cursorTrail.enabled, label: "Enabled" },
    particleRadius: {
      value: d.cursorTrail.particleRadius,
      min: 0.5,
      max: 80,
      step: 0.5,
      label: "Particle radius",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    particleAlpha: {
      value: d.cursorTrail.particleAlpha,
      min: 0,
      max: 1,
      step: 0.005,
      label: "Particle alpha",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    particleLifeMs: {
      value: d.cursorTrail.particleLifeMs,
      min: 50,
      max: 10000,
      step: 10,
      label: "Particle life (ms)",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    particleSpacingPx: {
      value: d.cursorTrail.particleSpacingPx,
      min: 0.5,
      max: 80,
      step: 0.5,
      label: "Particle spacing (px)",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    maxEmitPerTick: {
      value: d.cursorTrail.maxEmitPerTick,
      min: 1,
      max: 200,
      step: 1,
      label: "Max emit/tick",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    spreadMinPx: {
      value: d.cursorTrail.spreadMinPx,
      min: 0,
      max: 80,
      step: 0.5,
      label: "Spread min (px)",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    spreadMaxPx: {
      value: d.cursorTrail.spreadMaxPx,
      min: 0,
      max: 120,
      step: 0.5,
      label: "Spread max (px)",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    spinStrength: {
      value: d.cursorTrail.spinStrength,
      min: 0,
      max: 0.2,
      step: 0.001,
      label: "Spin strength",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    pushStrengthPx: {
      value: d.cursorTrail.pushStrengthPx,
      min: 0,
      max: 120,
      step: 1,
      label: "Push strength (px)",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    pushRadiusScale: {
      value: d.cursorTrail.pushRadiusScale,
      min: 0,
      max: 8,
      step: 0.05,
      label: "Push radius scale",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
    pushWobblePx: {
      value: d.cursorTrail.pushWobblePx,
      min: 0,
      max: 80,
      step: 1,
      label: "Push wobble (px)",
      render: (get) => get("Cursor Trail.cursorTrailEnabled") === true,
    },
  });
}

export function buildClickWaveFolder(d: EngineConfig) {
  return drawerFolder("Click Wave", {
    clickWaveEnabled: { value: d.clickWave.enabled, label: "Enabled" },
    clickWaveLifeMs: {
      value: d.clickWave.lifeMs,
      min: 80,
      max: 10000,
      step: 10,
      label: "Life (ms)",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
    clickWaveStartRadiusPx: {
      value: d.clickWave.startRadiusPx,
      min: 1,
      max: 120,
      step: 1,
      label: "Start radius (px)",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
    clickWaveMaxRadiusPx: {
      value: d.clickWave.maxRadiusPx,
      min: 4,
      max: 600,
      step: 2,
      label: "Max radius (px)",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
    clickWaveStartStrokeWidthPx: {
      value: d.clickWave.startStrokeWidthPx,
      min: 0.5,
      max: 80,
      step: 0.5,
      label: "Start stroke (px)",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
    clickWaveEndStrokeWidthPx: {
      value: d.clickWave.endStrokeWidthPx,
      min: 0.25,
      max: 40,
      step: 0.25,
      label: "End stroke (px)",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
    clickWaveMaxWaves: {
      value: d.clickWave.maxWaves,
      min: 1,
      max: 32,
      step: 1,
      label: "Max waves",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
    clickWavePushStrengthPx: {
      value: d.clickWave.pushStrengthPx,
      min: 0,
      max: 200,
      step: 1,
      label: "Push strength (px)",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
    clickWavePushBandScale: {
      value: d.clickWave.pushBandScale,
      min: 1,
      max: 8,
      step: 0.1,
      label: "Push band scale",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
    clickWaveStripeWhiteAlpha: {
      value: d.clickWave.stripeWhiteAlpha,
      min: 0,
      max: 1,
      step: 0.01,
      label: "Stripe white alpha",
      render: (get) => get("Click Wave.clickWaveEnabled") === true,
    },
  });
}

export function buildFlamesFolder(d: EngineConfig) {
  return drawerFolder("Background Flames", {
    flamesEnabled: { value: d.flames.enabled, label: "Enabled" },
    flamesDirection: {
      value: d.flames.direction,
      options: { Up: "up", Down: "down", Left: "left", Right: "right" } as const,
      label: "Direction",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesMinWidthPct: {
      value: d.flames.minWidthRatio * 100,
      min: 0.1,
      max: 50,
      step: 0.1,
      label: "Width min %",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesMaxWidthPct: {
      value: d.flames.maxWidthRatio * 100,
      min: 0.1,
      max: 50,
      step: 0.1,
      label: "Width max %",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesMinHeightPct: {
      value: d.flames.minHeightRatio * 100,
      min: 0.1,
      max: 50,
      step: 0.1,
      label: "Height min %",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesMaxHeightPct: {
      value: d.flames.maxHeightRatio * 100,
      min: 0.1,
      max: 50,
      step: 0.1,
      label: "Height max %",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesBaseSpeed: {
      value: d.flames.baseSpeedPxPerSec,
      min: 1,
      max: 500,
      step: 1,
      label: "Base speed (px/s)",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesSpeedVariation: {
      value: d.flames.speedVariation,
      min: 0,
      max: 1,
      step: 0.01,
      label: "Speed variation",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesSpawnInterval: {
      value: d.flames.spawnIntervalMs,
      min: 20,
      max: 5000,
      step: 10,
      label: "Spawn interval (ms)",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesSpawnJitter: {
      value: d.flames.spawnJitterMs,
      min: 0,
      max: 2000,
      step: 10,
      label: "Spawn jitter (ms)",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesMaxActive: {
      value: d.flames.maxActive,
      min: 1,
      max: 200,
      step: 1,
      label: "Max active",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesEdgeSharpness: {
      value: d.flames.edgeSharpness,
      min: 0,
      max: 1,
      step: 0.01,
      label: "Edge sharpness",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesOpacityMin: {
      value: d.flames.opacityMin,
      min: 0,
      max: 1,
      step: 0.01,
      label: "Opacity min",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
    flamesOpacityMax: {
      value: d.flames.opacityMax,
      min: 0,
      max: 1,
      step: 0.01,
      label: "Opacity max",
      render: (get) => get("Background Flames.flamesEnabled") === true,
    },
  });
}
