import fs from "node:fs";
import path from "node:path";
import { normalizeSvg } from "./normalize";
import type { Palette } from "./palette";

const root = process.cwd();
export const DEFAULT_SVG_DIR = path.join(root, "src/components/icon/_svg");
export const DEFAULT_CSS_PATH = path.join(root, "src/styles/_colors.css");
export const DEFAULT_DTS_PATH = path.join(
  root,
  "src/components/icon/icons.gen.d.ts"
);
export const DEFAULT_AMBIENT_DTS_PATH = DEFAULT_DTS_PATH.replace(
  /\.d\.ts$/,
  ".ambient.d.ts"
);

// NOTE: keep this shape in sync with the IconEntry declared inside renderAmbientDts() below.
export interface IconEntry {
  body: string;
  variant: "mono" | "duo";
  viewBox: string;
}

export type Registry = Record<string, IconEntry>;

export function buildRegistry(
  svgDir: string,
  palette: Palette
): { registry: Registry; warnings: string[] } {
  const registry: Registry = {};
  const warnings: string[] = [];
  const files = fs.existsSync(svgDir)
    ? fs
        .readdirSync(svgDir)
        .filter((f) => f.endsWith(".svg"))
        .sort()
    : [];
  for (const file of files) {
    const name = file.replace(/\.svg$/, "");
    const svg = fs.readFileSync(path.join(svgDir, file), "utf8");
    const { icon, warnings: w } = normalizeSvg(svg, palette, name);
    registry[name] = icon;
    warnings.push(...w);
  }
  return { registry, warnings };
}

export function renderModule(registry: Registry): string {
  return `export const ICONS = ${JSON.stringify(registry)};\n`;
}

export function renderDts(registry: Registry): string {
  const names = Object.keys(registry);
  const duo = names.filter((n) => registry[n].variant === "duo");
  const union = (xs: string[]) =>
    xs.length ? xs.map((n) => JSON.stringify(n)).join(" | ") : "never";
  return `// AUTO-GENERATED by dev/vite/icons — do not edit. Run \`pnpm run icons:types\` to regenerate.
export type IconName = ${union(names)};
export type DuoIconName = ${union(duo)};
`;
}

// Must have no top-level exports (script-context) so `declare module` augments rather than replaces the ambient module.
export function renderAmbientDts(): string {
  return `// AUTO-GENERATED by dev/vite/icons — do not edit.
declare module "virtual:icons" {
  // NOTE: keep in sync with the IconEntry interface in registry.ts.
  export interface IconEntry {
    body: string;
    viewBox: string;
    variant: "mono" | "duo";
  }
  export const ICONS: Record<string, IconEntry>;
}
`;
}
