import type { EngineConfig } from "@necatikcl/stripes-engine";

/** Designer-authored production config. Lab-only state is intentionally excluded. */
export const SPEAKER_SHADER_CONFIG = {
  transform: { fit: "width", zoom: 1, panX: 0, panY: 0 },
  adjustments: {
    brightness: 0.64,
    exposure: 2,
    contrast: 1.38,
    blackPoint: 0,
    whitePoint: 1,
    gamma: 0.88,
    invert: true,
    posterizeLevels: 0,
    thresholdBias: 0.07,
    noiseAmount: 1,
    blurRadius: 0,
    sharpenAmount: 0,
  },
  background: {
    color: 1315860,
    transparent: false,
    gradient: {
      enabled: false,
      direction: "topToBottom",
      stopCount: 3,
      stops: [8331002, 15349737, 16757594, 9752907],
      hueDriftDeg: 0,
      saturationBoost: 0,
    },
    grid: {
      enabled: false,
      cellWidth: 32,
      cellHeight: 32,
      gapX: 4,
      gapY: 4,
      cornerRadius: 0,
      color: 15987699,
      opacity: 1,
    },
    stars: {
      enabled: true,
      density: 2,
      sizePx: 12,
      sizeRandomness: 1,
      tiltAngleDeg: -15,
      twinkleSpeed: 1,
      twinkleAmount: 0.7,
      opacity: 1,
      color: 16777215,
    },
    meteors: {
      enabled: true,
      ratePerSec: 1.3199999999999998,
      maxActive: 16,
      radiantAngleDeg: -15,
      angleJitterDeg: 30,
      speedScale: 0.27,
      speedVariation: 1,
      tailLengthScale: 0.20999999999999996,
      tailLengthVariation: 0.62,
      thicknessScale: 0.44999999999999996,
      thicknessVariation: 0.64,
      lifetimeMinMs: 350,
      lifetimeMaxMs: 2630,
      brightness: 1,
      headGlow: 1,
      pushPx: 9.5,
      pushFalloffScale: 1,
      fadeInMs: 80,
      fadeOutMs: 580,
      seed: 1,
    },
  },
  // Overlay rest look from Speaker Frames panel → Copy config.
  grid: {
    cellWidth: 9,
    cellHeight: 15,
    gapX: 6.5,
    gapY: 0,
    cornerRadius: 0,
    orientation: "vertical",
    angleDeg: 45,
    rotationMode: "cell",
    overlapAmount: 0,
    streamGapWave: {
      enabled: false,
      squeeze: 0.23,
      wavelengthCells: 10,
      speed: -2.66,
      phaseDeg: -180,
    },
  },
  stripes: [
    { color: 0xb8_b8_b8, startFrom: 0, width: 0.5, opacity: 0 },
    { color: 0xd0_d0_d0, startFrom: 0.1644, width: 1, opacity: 0 },
    { color: 0xd0_d0_d0, startFrom: 0.4418, width: 1.5, opacity: 1 },
    { color: 0x2a_2a_2a, startFrom: 0.6357, width: 2, opacity: 1 },
    { color: 0x7a_7a_7a, startFrom: 0.7494, width: 3, opacity: 1 },
    { color: 0x3d_3d_3d, startFrom: 0.7104, width: 2.5, opacity: 1 },
    { color: 0xb3_b3_b3, startFrom: 0.7724, width: 4.5, opacity: 1 },
    { color: 0xcf_cf_cf, startFrom: 0.7864, width: 4, opacity: 1 },
    { color: 0xe6_e6_e6, startFrom: 0.7946, width: 4.5, opacity: 1 },
    { color: 0xf5_f5_f5, startFrom: 0.7988, width: 5, opacity: 1 },
  ],
  stripesEnabled: true,
  fieldScale: 0.58,
  maxFps: 0,
  reveal: {
    enabled: true,
    type: "water",
    wave: {
      position: "center",
      durationMs: 500,
      softness: 0.68,
      waviness: 1,
    },
    assembly: {
      sliceSizePx: 40,
      speedMinMs: 300,
      speedMaxMs: 1600,
      staggerMs: 900,
      scatterPx: 50,
      angleJitterDeg: 22,
      blurPx: 17.5,
      blurStart: 0.45,
    },
    turbulence: {
      speedMinMs: 400,
      speedMaxMs: 2600,
      staggerMs: 1400,
      intensity: 1,
      detail: 0.5,
      glow: 0.6,
    },
    glitch: {
      speedMinMs: 200,
      speedMaxMs: 1400,
      staggerMs: 1200,
      intensity: 1,
      detail: 0.5,
      glow: 0.8,
    },
    vortex: {
      speedMinMs: 300,
      speedMaxMs: 1400,
      staggerMs: 2600,
      intensity: 1,
      detail: 0.5,
      glow: 0.7,
      swirl: 1,
    },
    blackhole: {
      speedMinMs: 260,
      speedMaxMs: 1050,
      staggerMs: 3600,
      intensity: 1,
      detail: 0.5,
      glow: 0.7,
      swirl: 1.2,
      formMs: 1150,
      collapseMs: 420,
      arms: 3,
      lensing: 1,
      horizon: 0.12,
    },
    whirlpool: {
      durationMs: 5600,
      turns: 4,
      tightness: 0.22,
      streak: 0.6,
      glow: 0.4,
    },
    water: {
      durationMs: 950,
      settleMs: 520,
      rows: 5,
      intensity: 1.5,
      wobble: 0.7,
      refraction: 1.3,
      softness: 0.35,
    },
  },
  sparkle: {
    gaps: { enabled: false, coverage: 0, speed: 1 },
    width: {
      enabled: true,
      coverage: 0.5,
      swingPx: 2,
      swingPeriodMin: 0.5,
      swingPeriodMax: 1,
    },
    stripe: {
      enabled: true,
      coverage: 0.2,
      maxBrightness: 0.1,
      speed: 0.2,
      thickestCount: 4,
      hueDriftDeg: 0,
      saturationBoost: 0.26,
    },
    motion: {
      enabled: false,
      amplitudePx: 0.5,
      staggerPx: 1,
      maxOffsetPx: 36.5,
      speed: 0.55,
      direction: "rightToLeft",
    },
  },
  stripeDots: {
    enabled: true,
    density: 0.8,
    randomVisibility: 1,
    sizePx: 1.5,
    brightness: 0.13,
    hueDriftDeg: 0,
    saturationBoost: 0,
  },
  stripeBorder: { enabled: true, minWidthPx: 4, density: 0.02 },
  gridLines: { enabled: false, brightness: 0, density: 0.01 },
  frames: {
    enabled: true,
    luminanceThreshold: 0.57,
    highlightedStripeCount: 13,
    groupDistanceCells: 2,
    color: 0xff_bf_14,
    fontSizePx: 8,
    coordinateColor: 16777215,
  },
  flames: {
    enabled: true,
    direction: "upDown",
    minWidthRatio: 0.005,
    maxWidthRatio: 0.02,
    minHeightRatio: 0.02,
    maxHeightRatio: 0.04,
    baseSpeedPxPerSec: 30,
    speedVariation: 1,
    spawnIntervalMs: 80,
    spawnJitterMs: 80,
    maxActive: 25,
    edgeSharpness: 1,
    opacityMin: 0.3,
    opacityMax: 0.8999999999999999,
    vortexSingular: {
      segCount: 22,
      segSpacingPx: 10,
      turnRate: 0.9,
      turnVariation: 0.8,
      visibleMinMs: 7000,
      visibleMaxMs: 13000,
      hiddenMinMs: 800,
      hiddenMaxMs: 2600,
      lifeMinMs: 12000,
      lifeMaxMs: 24000,
      edgeMarginRatio: 0.12,
    },
  },
  edgeMask: {
    enabled: true,
    start: 0,
    end: 0.09999999999999998,
    power: 0.6000000000000001,
    sides: { top: true, right: true, bottom: true, left: true },
  },
  cursorTrail: {
    enabled: true,
    type: "default",
    particleRadius: 160,
    particleAlpha: 0.1,
    particleLifeMs: 530,
    particleLifeJitterMs: 100,
    emitterVelocitySmoothing: 0.7,
    particleVelocityScale: 0.01,
    particleTangentVelocity: 1.65,
    particleDamping: 0.96,
    particleSpacingPx: 3,
    maxEmitPerTick: 10,
    spreadMinPx: 1,
    spreadMaxPx: 20,
    spinStrength: 0.04,
    densityRadiusMinScale: 0.2,
    densityRadiusLifeScale: 1,
    pushRadiusScale: 0.9,
    pushStrengthPx: 160,
    pushLagPx: 0,
    pushWobblePx: 12,
    pushLeadBlackAlpha: 0,
    constellation: {
      radiusScale: 0.31,
      starDensity: 1,
      starSizePx: 2.2,
      starSizeRandomness: 0.77,
      starGrowScale: 1.35,
      starPushPx: 1.9,
      twinkleAmount: 0.18,
      twinkleSpeed: 1,
      linkThicknessPx: 2.9,
      linkBrightness: 1,
      linkGrooveDepth: 1,
      linkShearPx: 13.5,
      linkMaxDistScale: 0.2184,
      linkFormMs: 210,
      linkHoldMs: 0,
      linkDissolveMs: 540,
      maxLinks: 48,
      maxStars: 64,
      pulseEnabled: true,
      pulseDurationMs: 700,
      pulseCoreLenPx: 3.4,
      pulseTailLenPx: 27,
      pulseBrightness: 1,
      pulseRelayHops: 2,
      pulseCooldownMs: 900,
      flareMs: 460,
      flareScale: 0.85,
      polygonFlashEnabled: true,
      polygonFlashStrength: 1,
    },
    comet: {
      nodeCount: 13,
      headStiffness: 5200,
      headDamping: 104,
      chainStiffness: 4200,
      chainDamping: 80,
      maxLinkPx: 22,
      headRadiusPx: 10.6,
      tailRadiusPx: 3.2,
      stretchThinning: 0.62,
      smoothUnionPx: 5.4,
      bodyBrightness: 1,
      auraStrength: 1,
      bodyPushPx: 12,
      presenceRiseRate: 15,
      presenceFallRate: 2.6,
      embersEnabled: true,
      emberRatePerSec: 92,
      emberMaxCount: 210,
      emberSizePx: 2.9,
      emberSpeedMinPxPerSec: 26,
      emberSpeedMaxPxPerSec: 56,
      emberSpreadRad: 0.85,
      emberLifetimeMinMs: 560,
      emberLifetimeMaxMs: 1400,
      emberBrightness: 1,
      emberFadeInFraction: 0.12,
      seed: 10368889,
    },
  },
  clickWave: {
    enabled: true,
    type: "default",
    lifeMs: 630,
    startRadiusPx: 6,
    maxRadiusPx: 120,
    startStrokeWidthPx: 24,
    endStrokeWidthPx: 12,
    maxWaves: 12,
    pushStrengthPx: 38,
    pushBandScale: 3.2,
    stripeWhiteAlpha: 0.5,
    detonation: {
      maxConcurrent: 4,
      ringReachPx: 168,
      ringDurationMs: 600,
      ringThicknessPx: 24,
      ringRefractionPx: 20,
      flashRadiusPx: 24,
      flashDurationMs: 80,
      flashBrightness: 1,
      debrisCount: 24,
      debrisSpeedPxPerSec: 315,
      debrisSpeedVariation: 0.317,
      debrisDrag: 1.55,
      debrisGravityPxPerSec2: 360,
      debrisLifetimeMs: 1060,
      debrisLifetimeVariation: 0.302,
      debrisSizePx: 2.6,
      debrisBrightness: 1,
      craterRadiusPx: 118,
      craterDepth: 1,
      craterRelaxFastMs: 260,
      craterRelaxSlowMs: 1450,
      craterLifeMs: 3400,
      craterRimStrength: 1,
      seed: 1,
    },
  },
  letters: {
    enabled: false,
    mode: "random",
    colorMode: "white",
    color: 16777215,
    coverage: 0.1,
    positionX: 0.5,
    positionY: 0.5,
    areaWidth: 1,
    areaHeight: 1,
    text: "CLOUDFLARE",
    textCopies: 16,
    fontFamily: "Geist Mono Medium",
    sizeScale: 0.9,
    shuffleSpeed: 1,
  },
  colors: {
    mode: "luminance",
    stripeBlendMode: "normal",
    imageColorLightness: 0,
    imageColorDensity: 0,
    imageColorRemoveThin: 0,
    imageColorBoostThick: 0.8,
    autoDetectBackground: false,
    backgroundColor: 0,
    gradient: {
      enabled: false,
      direction: "topToBottom",
      stopCount: 3,
      stops: [8331002, 15415273, 16757593, 9752907],
      hueDriftDeg: 20,
      saturationBoost: 0.35,
    },
  },
  renderMode: "sharp",
  // The panel authors 0..2; the engine clamps to 1 at normalize time.
  renderIntensity: 2,
  renderParams: [0, 0.5, 0.5, 0.5],
  renderColorA: 2236962,
  renderColorB: 16777215,
} satisfies EngineConfig;

export const SPEAKER_SHADER_MAX_DPR = 1.75;
