export type ConnectShaderConfig = {
  speed: number;
  shapeType: "spiral" | "plane" | "helix" | "ribbon" | "torus" | "mobius" | "saddle" | "waveSheet" | "cone" | "disc";
  shapeWidth: number;
  twistX: number;
  twistY: number;
  shapeRadius: number;
  shapeConeRadiusStart: number;
  shapeConeRadiusEnd: number;
  shapeTube: number;
  shapeBend: number;
  shapePitch: number;
  shapeAmplitude: number;
  shapeTurns: number;
  shapeWaveFreq: number;
  cylinderLength: number;
  wavesX: number;
  wavesY: number;
  displacementHeight: number;
  speedX: number;
  speedY: number;
  fillColor: string;
  fillColor2: string;
  fillGradScale: number;
  fillAlpha: number;
  fillLow: number;
  fillHigh: number;
  fillRadius: number;
  lineColor: string;
  lineCount: number;
  lineWidth: number;
  lineAlpha: number;
  lineFadeLow: number;
  lineFadeHigh: number;
  hatchAngle: number;
  hatchLift: number;
  hatchSpacing: number;
  hatchCell: number;
  hatchFill: number;
  dashMin: number;
  dashMax: number;
  hatchDensity: number;
  densityFloor: number;
  hatchDrift: number;
  waveGate: number;
  envCenter: number;
  envSlope: number;
  envWidth: number;
  emitCount: number;
  emitAmount: number;
  emitSpeed: number;
  emitDist: number;
  emitFall: number;
  emitSize: number;
  emitStretch: number;
  emitAlpha: number;
  emitPaleColor: string;
  emitSalmonColor: string;
  emitOrangeColor: string;
  emitAmberColor: string;
  emitDeepColor: string;
  paleColor: string;
  salmonColor: string;
  orangeColor: string;
  amberColor: string;
  deepColor: string;
  cameraZ: number;
  cameraY: number;
  cameraFov: number;
  renderDpr: number;
  shapeMeshQuality: number;
  renderAntialias: boolean;
  postEnabled: boolean;
  postPreset: "off" | "soft" | "cinematic" | "dreamy" | "punchy" | "bloom" | "retro" | "flare" | "custom";
  postBlur: number;
  postBokeh: number;
  postBokehThreshold: number;
  postChroma: number;
  postVignette: number;
  postGrain: number;
  postContrast: number;
  postSaturation: number;
  postExposure: number;
  postSharpness: number;
  postWarmth: number;
  postProgBlur: number;
  postProgFocus: number;
  postFlare: number;
  postFlareSpread: number;
  postFlareThreshold: number;
  postFlareX: number;
  postFlareY: number;
};

export type ConnectShapeType = ConnectShaderConfig["shapeType"];

// @shader-config-start
export const CONNECT_SHADER_DEFAULTS = {
  speed: 0.15,
  shapeType: "spiral",
  shapeWidth: 21.5,
  twistX: 0.35,
  twistY: 0.35,
  shapeRadius: 10,
  shapeConeRadiusStart: 14,
  shapeConeRadiusEnd: 0.75,
  shapeTube: 3.5,
  shapeBend: 160,
  shapePitch: 28,
  shapeAmplitude: 6,
  shapeTurns: 1,
  shapeWaveFreq: 2,
  cylinderLength: 208,
  wavesX: 3,
  wavesY: 3,
  displacementHeight: 3.4,
  speedX: 0.025,
  speedY: 0.13,
  fillColor: "#ff7a1f",
  fillColor2: "#ffaf36",
  fillGradScale: 0.2,
  fillAlpha: 1,
  fillLow: 0.04,
  fillHigh: 0.88,
  fillRadius: 0,
  lineColor: "#e8481c",
  lineCount: 1186,
  lineWidth: 1,
  lineAlpha: 0.8,
  lineFadeLow: 0.35,
  lineFadeHigh: 0.72,
  hatchAngle: 90,
  hatchLift: 1.4,
  hatchSpacing: 0.22,
  hatchCell: 0.85,
  hatchFill: 0.22,
  dashMin: 0.15,
  dashMax: 0.95,
  hatchDensity: 8,
  densityFloor: 1,
  hatchDrift: 40,
  waveGate: 0.55,
  envCenter: 0.7,
  envSlope: 0.35,
  envWidth: 0.2,
  emitCount: 12000,
  emitAmount: 0.81,
  emitSpeed: 0.65,
  emitDist: 8,
  emitFall: 16,
  emitSize: 1,
  emitStretch: 13.9,
  emitAlpha: 0.95,
  emitPaleColor: "#ffe3d1",
  emitSalmonColor: "#ffb98c",
  emitOrangeColor: "#ff7a1f",
  emitAmberColor: "#ffa51f",
  emitDeepColor: "#e85d04",
  paleColor: "#ffe3d1",
  salmonColor: "#ffb98c",
  orangeColor: "#ff7a1f",
  amberColor: "#ffa51f",
  deepColor: "#e85d04",
  cameraZ: 18,
  cameraY: 4,
  cameraFov: 43,
  renderDpr: 1.75,
  shapeMeshQuality: 1,
  renderAntialias: true,
  postEnabled: true,
  postPreset: "off",
  postBlur: 0.86,
  postBokeh: 0.44,
  postBokehThreshold: 0.2,
  postChroma: 0,
  postVignette: 0,
  postGrain: 0,
  postContrast: 1.06,
  postSaturation: 1.32,
  postExposure: 1.13,
  postSharpness: 0.46,
  postWarmth: 1,
  postProgBlur: 0.33,
  postProgFocus: 0,
  postFlare: 0.05,
  postFlareSpread: 0.5,
  postFlareThreshold: 0.72,
  postFlareX: 0.58,
  postFlareY: 0.42,
} as const;
// @shader-config-end
