import { folder } from "leva";
import { loadControlDrawerOpen } from "../controls/drawerState";
import { CONNECT_SHADER_PARAM_DEFAULTS, type ConnectShaderParams } from "./params";

type ShowRef = { current: boolean };

function connectFolder(id: string, schema: Parameters<typeof folder>[0], showRef: ShowRef) {
  return folder(schema, {
    collapsed: !loadControlDrawerOpen(id, false),
    render: () => showRef.current,
  });
}

/** Right-panel Connect material folders (visible when Connect shader is selected). */
export function buildConnectShaderLevaFolders(params: ConnectShaderParams, showRef: ShowRef) {
  return {
    "Connect Wave": connectFolder(
      "Connect Wave",
      {
        connectSpeed: { value: params.speed, min: 0, max: 3, step: 0.05, label: "Speed" },
        connectWavesX: { value: params.wavesX, min: 0.2, max: 24, step: 0.1, label: "Waves X" },
        connectWavesY: { value: params.wavesY, min: 0.2, max: 24, step: 0.1, label: "Waves Y" },
        connectDisplacement: {
          value: params.displacementHeight,
          min: 0,
          max: 24,
          step: 0.05,
          label: "Displacement",
        },
        connectSpeedX: { value: params.speedX, min: 0, max: 0.6, step: 0.001, label: "Drift X" },
        connectSpeedY: { value: params.speedY, min: 0, max: 0.6, step: 0.001, label: "Drift Y" },
      },
      showRef,
    ),
    "Connect Shape": connectFolder(
      "Connect Shape",
      {
        connectShapeWidth: { value: params.shapeWidth, min: 8, max: 48, step: 0.5, label: "Surface width" },
        connectCylinderLength: {
          value: params.cylinderLength,
          min: 40,
          max: 260,
          step: 2,
          label: "Surface length",
        },
        connectTwistX: { value: params.twistX, min: 0.05, max: 2.5, step: 0.01, label: "Twist X" },
        connectTwistY: { value: params.twistY, min: 0.05, max: 2.5, step: 0.01, label: "Twist Y" },
        connectShapeRadius: { value: params.shapeRadius, min: 3, max: 36, step: 0.25, label: "Radius" },
        connectConeRadiusStart: {
          value: params.shapeConeRadiusStart,
          min: 0.5,
          max: 36,
          step: 0.25,
          label: "Cone base radius",
        },
        connectConeRadiusEnd: {
          value: params.shapeConeRadiusEnd,
          min: 0,
          max: 36,
          step: 0.25,
          label: "Cone apex radius",
        },
        connectShapeTube: { value: params.shapeTube, min: 0.5, max: 14, step: 0.1, label: "Tube radius" },
        connectShapeBend: {
          value: params.shapeBend,
          min: 0,
          max: 160,
          step: 1,
          label: "Arc bend °",
        },
        connectShapePitch: { value: params.shapePitch, min: 6, max: 90, step: 1, label: "Helix pitch" },
        connectShapeAmplitude: {
          value: params.shapeAmplitude,
          min: 0,
          max: 24,
          step: 0.25,
          label: "Shape amplitude",
        },
        connectShapeTurns: { value: params.shapeTurns, min: 0.25, max: 5, step: 0.05, label: "Turns / loops" },
        connectShapeWaveFreq: {
          value: params.shapeWaveFreq,
          min: 0.5,
          max: 8,
          step: 0.1,
          label: "Shape wave freq",
        },
        connectMeshQuality: {
          value: params.shapeMeshQuality,
          min: 0.25,
          max: 3,
          step: 0.05,
          label: "Mesh density",
        },
      },
      showRef,
    ),
    "Connect Fill": connectFolder(
      "Connect Fill",
      {
        connectFillColor: { value: params.fillColor, label: "Fill color A" },
        connectFillColor2: { value: params.fillColor2, label: "Fill color B" },
        connectFillGradScale: {
          value: params.fillGradScale,
          min: 0.2,
          max: 6,
          step: 0.05,
          label: "Gradient scale",
        },
        connectFillRadius: { value: params.fillRadius, min: 0, max: 2, step: 0.02, label: "Fill radius" },
        connectFillAlpha: { value: params.fillAlpha, min: 0, max: 1, step: 0.01, label: "Fill opacity" },
        connectFillLow: { value: params.fillLow, min: 0, max: 1, step: 0.01, label: "Fill start" },
        connectFillHigh: { value: params.fillHigh, min: 0, max: 1, step: 0.01, label: "Fill peak" },
      },
      showRef,
    ),
    "Connect Lines": connectFolder(
      "Connect Lines",
      {
        connectLineColor: { value: params.lineColor, label: "Line color" },
        connectLineCount: { value: params.lineCount, min: 20, max: 1500, step: 2, label: "Line count" },
        connectLineWidth: { value: params.lineWidth, min: 0.4, max: 4, step: 0.05, label: "Width (px)" },
        connectLineAlpha: { value: params.lineAlpha, min: 0, max: 1, step: 0.01, label: "Opacity" },
        connectLineFadeLow: { value: params.lineFadeLow, min: 0, max: 1, step: 0.01, label: "Dissolve low" },
        connectLineFadeHigh: {
          value: params.lineFadeHigh,
          min: 0,
          max: 1,
          step: 0.01,
          label: "Dissolve high",
        },
      },
      showRef,
    ),
    "Connect Hatch": connectFolder(
      "Connect Hatch",
      {
        connectHatchAngle: { value: params.hatchAngle, min: 0, max: 180, step: 0.5, label: "Angle (deg)" },
        connectHatchLift: { value: params.hatchLift, min: 0, max: 14, step: 0.05, label: "Float height" },
        connectHatchSpacing: {
          value: params.hatchSpacing,
          min: 0.02,
          max: 0.8,
          step: 0.005,
          label: "Row spacing",
        },
        connectHatchCell: { value: params.hatchCell, min: 0.2, max: 12, step: 0.05, label: "Cell length" },
        connectHatchFill: { value: params.hatchFill, min: 0.1, max: 1, step: 0.01, label: "Thickness" },
        connectDashMin: { value: params.dashMin, min: 0.01, max: 1, step: 0.01, label: "Dash min" },
        connectDashMax: { value: params.dashMax, min: 0.05, max: 1, step: 0.01, label: "Dash max" },
        connectHatchDensity: { value: params.hatchDensity, min: 0, max: 8, step: 0.02, label: "Density" },
        connectDensityFloor: {
          value: params.densityFloor,
          min: 0,
          max: 1,
          step: 0.005,
          label: "Density floor",
        },
        connectHatchDrift: { value: params.hatchDrift, min: 0, max: 40, step: 0.1, label: "Drift" },
        connectWaveGate: { value: params.waveGate, min: 0, max: 1, step: 0.01, label: "Wave gating" },
        connectEnvCenter: { value: params.envCenter, min: 0, max: 1.2, step: 0.01, label: "Swath center" },
        connectEnvSlope: { value: params.envSlope, min: -1, max: 1, step: 0.01, label: "Swath slope" },
        connectEnvWidth: { value: params.envWidth, min: 0.03, max: 0.6, step: 0.005, label: "Swath width" },
      },
      showRef,
    ),
    "Connect Particles": connectFolder(
      "Connect Particles",
      {
        connectEmitCount: { value: params.emitCount, min: 500, max: 40000, step: 500, label: "Count" },
        connectEmitAmount: { value: params.emitAmount, min: 0, max: 1, step: 0.01, label: "Amount" },
        connectEmitSpeed: { value: params.emitSpeed, min: 0, max: 6, step: 0.01, label: "Launch rate" },
        connectEmitDist: { value: params.emitDist, min: 0, max: 50, step: 0.1, label: "Fly distance" },
        connectEmitFall: { value: params.emitFall, min: 0, max: 80, step: 0.25, label: "Fall w/ wave" },
        connectEmitSize: { value: params.emitSize, min: 0.2, max: 16, step: 0.05, label: "Size (units)" },
        connectEmitStretch: { value: params.emitStretch, min: 1, max: 20, step: 0.1, label: "Stretch" },
        connectEmitAlpha: { value: params.emitAlpha, min: 0, max: 1, step: 0.01, label: "Opacity" },
        connectEmitPaleColor: { value: params.emitPaleColor, label: "Pale" },
        connectEmitSalmonColor: { value: params.emitSalmonColor, label: "Salmon" },
        connectEmitOrangeColor: { value: params.emitOrangeColor, label: "Orange" },
        connectEmitAmberColor: { value: params.emitAmberColor, label: "Amber" },
        connectEmitDeepColor: { value: params.emitDeepColor, label: "Deep" },
      },
      showRef,
    ),
    "Connect Colors": connectFolder(
      "Connect Colors",
      {
        connectPaleColor: { value: params.paleColor, label: "Pale" },
        connectSalmonColor: { value: params.salmonColor, label: "Salmon" },
        connectOrangeColor: { value: params.orangeColor, label: "Orange" },
        connectAmberColor: { value: params.amberColor, label: "Amber" },
        connectDeepColor: { value: params.deepColor, label: "Deep" },
      },
      showRef,
    ),
  };
}

export function connectShaderParamsFromLevaValues(values: Record<string, unknown>): ConnectShaderParams {
  return {
    speed: Number(values.connectSpeed),
    wavesX: Number(values.connectWavesX),
    wavesY: Number(values.connectWavesY),
    displacementHeight: Number(values.connectDisplacement),
    speedX: Number(values.connectSpeedX),
    speedY: Number(values.connectSpeedY),
    shapeWidth: Number(values.connectShapeWidth),
    cylinderLength: Number(values.connectCylinderLength),
    twistX: Number(values.connectTwistX),
    twistY: Number(values.connectTwistY),
    shapeRadius: Number(values.connectShapeRadius),
    shapeConeRadiusStart: Number(values.connectConeRadiusStart),
    shapeConeRadiusEnd: Number(values.connectConeRadiusEnd),
    shapeTube: Number(values.connectShapeTube),
    shapeBend: Number(values.connectShapeBend),
    shapePitch: Number(values.connectShapePitch),
    shapeAmplitude: Number(values.connectShapeAmplitude),
    shapeTurns: Number(values.connectShapeTurns),
    shapeWaveFreq: Number(values.connectShapeWaveFreq),
    shapeMeshQuality: Number(values.connectMeshQuality),
    fillColor: String(values.connectFillColor),
    fillColor2: String(values.connectFillColor2),
    fillGradScale: Number(values.connectFillGradScale),
    fillRadius: Number(values.connectFillRadius),
    fillAlpha: Number(values.connectFillAlpha),
    fillLow: Number(values.connectFillLow),
    fillHigh: Number(values.connectFillHigh),
    lineColor: String(values.connectLineColor),
    lineCount: Number(values.connectLineCount),
    lineWidth: Number(values.connectLineWidth),
    lineAlpha: Number(values.connectLineAlpha),
    lineFadeLow: Number(values.connectLineFadeLow),
    lineFadeHigh: Number(values.connectLineFadeHigh),
    hatchAngle: Number(values.connectHatchAngle),
    hatchLift: Number(values.connectHatchLift),
    hatchSpacing: Number(values.connectHatchSpacing),
    hatchCell: Number(values.connectHatchCell),
    hatchFill: Number(values.connectHatchFill),
    dashMin: Number(values.connectDashMin),
    dashMax: Number(values.connectDashMax),
    hatchDensity: Number(values.connectHatchDensity),
    densityFloor: Number(values.connectDensityFloor),
    hatchDrift: Number(values.connectHatchDrift),
    waveGate: Number(values.connectWaveGate),
    envCenter: Number(values.connectEnvCenter),
    envSlope: Number(values.connectEnvSlope),
    envWidth: Number(values.connectEnvWidth),
    emitCount: Number(values.connectEmitCount),
    emitAmount: Number(values.connectEmitAmount),
    emitSpeed: Number(values.connectEmitSpeed),
    emitDist: Number(values.connectEmitDist),
    emitFall: Number(values.connectEmitFall),
    emitSize: Number(values.connectEmitSize),
    emitStretch: Number(values.connectEmitStretch),
    emitAlpha: Number(values.connectEmitAlpha),
    emitPaleColor: String(values.connectEmitPaleColor),
    emitSalmonColor: String(values.connectEmitSalmonColor),
    emitOrangeColor: String(values.connectEmitOrangeColor),
    emitAmberColor: String(values.connectEmitAmberColor),
    emitDeepColor: String(values.connectEmitDeepColor),
    paleColor: String(values.connectPaleColor),
    salmonColor: String(values.connectSalmonColor),
    orangeColor: String(values.connectOrangeColor),
    amberColor: String(values.connectAmberColor),
    deepColor: String(values.connectDeepColor),
    renderDpr: CONNECT_SHADER_PARAM_DEFAULTS.renderDpr,
    renderAntialias: CONNECT_SHADER_PARAM_DEFAULTS.renderAntialias,
  };
}
